NSX-T Network backing of VM creation
juju/juju pull request #11488
Opened 2020-04-22 23:33 UTC by hashneo

## Please provide the following details to expedite Pull Request review:

### Checklist

 - [ ] Checked if it requires a [pylibjuju](https://github.com/juju/python-libjuju) change?
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR?
 - [ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed?
 - [ ] Do comments answer the question of why design decisions were made?

----

## Description of change

When you bootstrapped a vSphere instance specified the external and primary networks on an NSX-T network port, Juju ignored the Opaque Network type and assumed it was a plain switch creating a VM using this backing type. vSphere would create dummy network port and the bootstrapping would be disconnected from the network.

## QA steps

*Please replace with how we can verify that the change works?*

```sh
juju bootstrap home vsp-controller --default-model lab --config primary-network=<nsx-t int net> --config external-network=<nsx-t ext net> --config datastore=<ds> 
```

## Documentation changes

none

## Bug reference

none

2020-12-15 09:58 UTC, SimonRichardson requested changes
Can we get some tests around this, so we don't break it in the future.

2020-12-15 09:58 UTC, SimonRichardson commented on provider/vsphere/internal/vsphereclient/createvm.go
> +			}
```suggestion
			opaqueSummary, ok := network.Summary.(*types.OpaqueNetworkSummary)
			if !ok {
				return nil, errors.NotValidf("network summary %q", networkSummary.Network.Type)
			}
			networkBacking = &types.VirtualEthernetCardOpaqueNetworkBackingInfo{
				OpaqueNetworkId:   opaqueSummary.OpaqueNetworkId,
				OpaqueNetworkType: opaqueSummary.OpaqueNetworkType,
			}
```

2020-12-15 09:58 UTC, SimonRichardson commented on provider/vsphere/internal/vsphereclient/createvm.go
> +			return nil, errors.NewNotValid(nil, fmt.Sprintf("Unknown network type %q", networkSummary.Network.Type))
```suggestion
			return nil, errors.NotValidf("Unknown network type %q", networkSummary.Network.Type)
```

2020-12-17 21:41 UTC, petevg commented
Closing to clean up old PRs. Feel free to re-open when/if someone returns to this!

2020-12-17 21:41 UTC, closed without merging