Add ResolveCharms to charms api and facade
juju/juju pull request #11923
Opened 2020-08-20 16:10 UTC by hmlanigan

## Description of change

As part of adding CharmHub charms to the deploy code.  Consolidate ResolveCharms into the charms api and facades.  This also moves resolution of the charm from the client to the controller for the CharmStore charms as well.  This functionality
 is needed to meet CharmHub requirements.  It also prevents a case where the juju client could find a charm, but the controller could not find it to download and deploy.   We can then exit sooner.

## QA steps

Unit tests should work.  Full QA once this new api call is used by the application deployer and upgrade charm.

2020-08-20 16:18 UTC, SimonRichardson requested changes
I think we should move to Origin and encapsulate the `cs.Channel` into the `Origin.Channel.Risk`.

2020-08-20 16:18 UTC, SimonRichardson commented on api/charms/client.go
> +			Channel:   string(curl.Channel),
Can we pass origin here, might be more useful in the future?

2020-08-20 16:18 UTC, SimonRichardson commented on api/charms/client.go
> +			Channel:         csparams.Channel(r.Channel),
This should be origin, will help in the future.

2020-08-20 16:18 UTC, SimonRichardson commented on apiserver/facades/client/charms/resolver.go
> +func (c *chResolver) ResolveWithPreferredChannel(*charm.URL, csparams.Channel) (*charm.URL, csparams.Channel, []string, error) {
```suggestion
func (c *chResolver) ResolveWithPreferredChannel(*charm.URL, Origin) (*charm.URL, Origin, []string, error) {
```

2020-08-20 20:50 UTC, hmlanigan commented
@SimonRichardson: we need to look at Origin.Channel.Risk, the current values are good for the CharmHub, but are only a subset of the csparams.Channel.

2020-08-20 21:27 UTC, SimonRichardson commented
I think the validation function may only need to run for charmhub and not anything else?

2020-08-24 16:03 UTC, SimonRichardson approved these changes

2020-08-24 16:03 UTC, SimonRichardson commented on apiserver/facades/client/charms/resolver.go
> +
Doing exactly the same thing I'm currently doing :+1:

2020-08-24 16:03 UTC, SimonRichardson commented on cmd/juju/application/bundle/bundle.go
> +	sort.Strings(principalApps)
Excellent:+1:

2020-08-24 17:16 UTC, hmlanigan commented
$$merge$$

2020-08-24 17:38 UTC, merged