Validate model upgrade
juju/juju pull request #11936
Opened 2020-08-26 11:05 UTC by SimonRichardson

## Description of change

The following code validates a machine under a given model, but ignores
controller models.

The code handles connecting to the state pool, to get a model that was
requested and then ensuring that there isn't a machine under going a
upgrade series.

One downside to doing this way, is that if there are any models with
1000s of machines, this could be really slow. Unfortunately there isn't
really much we can do at this stage. Maybe in subsequent commit we can
make a bulk method for checking if any machines in a model are
upgrading...

## QA steps

*Please replace with how we can verify that the change works?*

```sh
QA steps here
```

## Documentation changes

*Please replace with any notes about how it affects current user workflow? CLI? API?*

## Bug reference

*Please add a link to any bugs that this change is related to.*

2020-08-28 10:35 UTC, manadart requested changes
Couple of minor changes.

The other thing to consider here is that this isn't race-proof. We would need to include an assertion at the upgrade instigation (the update to model config) that no series upgrade locks were present for the model.

2020-08-28 10:35 UTC, manadart commented on apiserver/facades/client/modelmanager/modelmanager.go
> +		if err := m.validateSeriesUpgradeForSeriesUpgrade(st, args.Force); err != nil {
I'd rename this to some thing like `validateNoSeriesUpgrades`.

2020-08-28 10:35 UTC, manadart commented on apiserver/facades/client/modelmanager/modelmanager.go
> +			return errors.AlreadyExistsf("unexpected upgrade series lock for machine %q", machine.Id())
I don't think `AlreadyExists` is the right type of error; it's the kind of error you return when attempting to add/create something.

2020-08-28 10:35 UTC, manadart commented on apiserver/facades/client/modelmanager/validatemodelupgrades_test.go
> +	"github.com/juju/juju/provider/dummy"
Grouping.

2020-08-28 10:35 UTC, manadart commented on apiserver/facades/client/modelmanager/modelmanager.go
> +	machines, err := st.AllMachines()
It will be faster to add a new method to state for all the upgrade locks and just check that there are none.

2020-08-28 14:48 UTC, manadart approved these changes

2020-09-04 08:49 UTC, manadart commented
$$merge$$

2020-09-04 09:13 UTC, merged

2020-09-04 11:08 UTC, SimonRichardson commented
@manadart I may have worked out a way to do the model config lock check without changing any library, but would need to test it...

Essentially using regex for `^$` and if that exist don't upgrade.