update charm-resources help
juju/juju pull request #12708
Opened 2021-03-02 20:20 UTC by hmlanigan

Update charm-resources help message. Remove references to the charm store specifically, reference a repository instead to cover it and charm-hub.  Format similar to other help command output, with a specific Examples section.

## QA steps

```sh
juju charm-resources --help
```

2021-03-02 21:51 UTC, hmlanigan commented
!!build!!

2021-03-03 15:11 UTC, SimonRichardson requested changes

2021-03-03 15:11 UTC, SimonRichardson commented on cmd/juju/resource/charmresources.go
> +		return nil, errors.Errorf("charm-hub charms are not supported with the current controller, try upgrading the controller to a newer version")
Charm-hub is one word.

2021-03-03 20:59 UTC, SimonRichardson approved these changes

2021-03-03 21:03 UTC, hmlanigan commented
$$merge$$

2021-03-03 21:38 UTC, merged