openstack provider credentials should consider project domain id
juju/juju pull request #12838
Opened 2021-03-31 10:30 UTC by hemanthnakkina

juju autoload-credentials ignores the OS_PROJECT_DOMAIN_ID if set
and looks for only OS_PROJECT_DOMAIN_NAME. However there are cases
where openrc downloaded from OpenStack Dashboard for non-admin user
sets only OS_PROJECT_DOMAIN_ID. In these cases juju bootstrap fails
with authentication error since juju is not aware of project domain
id and project domain name is empty.
This change reads OS_PROJECT_DOMAIN_ID and sets in CredentialsAttribute
map. The same have been passed to the client for authentication
purpose.

## Checklist

-  Requires a go-goose change 
   https://github.com/go-goose/goose/pull/89

## QA steps

```sh
$ #Download openrc from OpenStack Horizon for a non-admin user
$ source openrc
$ # Add openstack cloud to juju using juju add-cloud
$ juju autoload-credentials
$ juju show-credentials # Check project-domain-id is set and project-domain-name is empty
$ juju bootstrap <cloud> <controller>
```

## Documentation changes
NA

## Bug reference
https://bugs.launchpad.net/juju/+bug/1772649

2021-04-01 18:36 UTC, hmlanigan commented
!!build!!

2021-04-01 19:45 UTC, hmlanigan requested changes
I have credentials for an openstack including an OS_PROJECT_ID.  Testing this change, the project id was set to empty string, not the value as expected.

$ juju show-credential serverstack hml
client-credentials:
  serverstack:
    hml:
      content:
        auth-type: userpass
        password: xxxxxx
        domain-name: ""
        project-domain-id: ""
        project-domain-name: user
        tenant-id: 3fbe7b5b19c348169e6ba85ac54decf0
        tenant-name: hml
        user-domain-name: user
        username: hml
        version: "3"

OS_REGION_NAME=region_one
OS_AUTH_VERSION=3
OS_AUTH_URL=http://x.x.x.x:5000/v3
OS_PROJECT_DOMAIN_NAME=user
OS_USERNAME=hml
OS_PROJECT_ID=3fbe7b5b19c348169e6ba85ac54decf0
OS_USER_DOMAIN_NAME=user
OS_PROJECT_NAME=hml
OS_PASSWORD=xxxxxx
OS_IDENTITY_API_VERSION=3

Also requires goose pr 89 to land, for go mod updates.

2021-04-01 19:56 UTC, hmlanigan commented
We also need to work out a story or notification for using older juju clients with the new credentials:
$ /snap/bin/juju version
2.8.10-focal-amd64
$ /snap/bin/juju bootstrap serverstack thursday-snap
ERROR finalizing "hml" credential for cloud "serverstack": unknown key "project-domain-id" (value "")

2021-04-05 07:31 UTC, hemanthnakkina commented
Updated go.mod to point to https://github.com/hemanthnakkina/goose/tree/issue88 to pick goose PR.
This is just for testing purpose. DO NOT MERGE this change.

Need to think on hmlanigan comments - the possibility of notification in case of using older juju clients with new credentials file.

2021-04-29 17:30 UTC, hmlanigan commented
@hemanthnakkina this pr needs to be rebased to the 2.9 branch and redirected there

2021-04-29 17:42 UTC, hmlanigan commented
Let's not worry about the different juju clients at this time.

2021-04-29 17:51 UTC, hmlanigan commented
credential information have been sent privately to resolve the issue found in qa

2021-09-22 13:59 UTC, hmlanigan commented
Closing as it's stale now, please reopen when the issues have been addressed.

2021-09-22 13:59 UTC, closed without merging