[vsphere] Add ability to specify local templates for vsphere
juju/juju pull request #12894
Opened 2021-04-19 13:27 UTC by gabriel-samfira

This PR adds ability to specify local templates via simplestreams.

This is still a draft. Will update README shortly.

2021-04-26 13:38 UTC, hmlanigan commented on provider/vsphere/internal/vsphereclient/client.go
> +	c.logger.Debugf("ListVMTemplates() path=%q", path)
Let's keep this log message at a Trace level

2021-04-26 19:10 UTC, gabriel-samfira commented
This PR still needs some new tests, but it should be ready for review.

2021-04-28 17:22 UTC, hmlanigan commented on provider/vsphere/vm_template.go
> +		return nil, "", errors.Trace(err)
This causes misleading error messages during bootstrap, when a template hasn't been created yet.

...
Launching controller instance(s) on boston-vsphere/Boston...
ERROR failed to fetch templates: path not found: juju-ci-root/Juju Controller (baf1f6a2-f6d7-44f1-8916-7165113f7f8f)/templates/focal/* not found
 - juju-dc6839-0 (arch=amd64 mem=3.5G) f81b245c98d18fec1564e6b374c346f1ef14394c9e836ee77e1e58754242a4f9"
Installing Juju agent on bootstrap instance

2021-04-28 17:26 UTC, hmlanigan commented on provider/vsphere/vm_template.go
> +		logger.Errorf("failed to fetch templates: %v", err)
This causes misleading error messages during bootstrap, when the folder for the bootstrapping controller hasn't been created yet.
```
...
Launching controller instance(s) on boston-vsphere/Boston...
ERROR failed to fetch templates: path not found: juju-ci-root/Juju Controller (baf1f6a2-f6d7-44f1-8916-7165113f7f8f)/templates/focal/* not found
 - juju-dc6839-0 (arch=amd64 mem=3.5G) f81b245c98d18fec1564e6b374c346f1ef14394c9e836ee77e1e58754242a4f9"
Installing Juju agent on bootstrap instance
...
```

2021-04-28 18:24 UTC, hmlanigan commented
During QA:

Bootstrap used the simplestreams defined template, but `juju deploy ubuntu --series focal` did not.  A new template was added to the "Juju Controller (<uuid)/templates/focal) folder, which was not created beforehand.  The simplestreams template is for focal: https://paste.ubuntu.com/p/VJsZTtVnV5/

2021-04-28 21:02 UTC, hmlanigan requested changes
The one issue found during QA that needs to be resolved, as well as items listed below.

2021-05-03 12:49 UTC, gabriel-samfira commented
> During QA:
> 
> Bootstrap used the simplestreams defined template, but `juju deploy ubuntu --series focal` did not. A new template was added to the "Juju Controller (<uuid)/templates/focal) folder, which was not created beforehand. The simplestreams template is for focal: https://paste.ubuntu.com/p/VJsZTtVnV5/

This is *probably* due to the fact that during bootstrap, juju grabbed the upstream ```jujud``` binary, which does not have the changes.

Make sure you also generate the agent metadata using:

```bash
juju-metadata generate-agents --stream proposed
``` 

This will look for packaged binaries in ```$HOME/.local/share/juju/tools/proposed/``` and build appropriate metadata for whatever it finds in there. I will update the PR description.

2021-05-03 18:29 UTC, gabriel-samfira commented on provider/vsphere/internal/vsphereclient/client.go
> +func (c *Client) VirtualMachineObjectToManagedObject(ctx context.Context, vmObject *object.VirtualMachine) (mo.VirtualMachine, error) {
This function essentially calls ```RetrieveOne()``` from the ```govmomi``` client and returns the result. Not sure a test would yield any more relevant results than the unit tests that already exist for the ```govmomi``` client.

Thoughts?

2021-05-04 19:26 UTC, hmlanigan commented
When using --build-agents, should need the juju metadata piece.    Redid the QA, as expected: when deploying ubuntu with focal, no new template was created, when deploying ubuntu with bionic, a new template was created.

2021-05-04 19:41 UTC, hmlanigan reviewed
A few small items to resolve, then I will approve and merge.

2021-05-04 19:41 UTC, hmlanigan commented on provider/vsphere/export_test.go
> +	"github.com/vmware/govmomi/vim25/types"
should be 2 stanza of imports

2021-05-04 19:41 UTC, hmlanigan commented on provider/vsphere/userdata_test.go
> +	c.Assert(string(result), jc.DeepEquals, expected)
Let's move to a new test method TestVsphereWindows.

2021-05-04 19:41 UTC, hmlanigan commented on provider/vsphere/vm_template.go
> +	"github.com/vmware/govmomi/vim25/types"
"GitHub.com/juju/juju/..." belong in the last import stanza.

Everything else in the selection, belongs in the 2nd import stanza

2021-05-04 19:41 UTC, hmlanigan commented on provider/vsphere/vm_template_test.go
> +	gc "gopkg.in/check.v1"
"github.com/juju/juju/..." should be in the last stanza, everything else in the selection, the 2nd stanza

2021-05-05 14:28 UTC, hmlanigan approved these changes
LGTM now, all testing is good.

2021-05-05 14:30 UTC, hmlanigan commented
!!build!!

2021-05-05 14:56 UTC, hmlanigan commented
$$merge$$

2021-05-05 15:23 UTC, merged