GCE: Allow inject of global http client
juju/juju pull request #13024
Opened 2021-05-26 15:28 UTC by SimonRichardson

The following code changes starts to lift the http client out from the
edge and into the constructor of the environ. Future commits should
allow us to pass in a http client on the construction of the environ
from the dependency engine. This is just the first step of many to do
that.

## QA steps

```sh
$ juju bootstrap google test 
```

## Bug reference

 - https://bugs.launchpad.net/juju/+bug/1928182
 - https://bugs.launchpad.net/juju/+bug/1899793

2021-05-26 23:35 UTC, hpidcock approved these changes

2021-05-26 23:35 UTC, hpidcock commented on provider/gce/environ.go
> +		HTTPClient: utils.GetHTTPClient(sslVerification),
Yeah agree this is a bit ugly.

2021-05-26 23:35 UTC, hpidcock commented on provider/gce/environ.go
> +	ctx := stdcontext.Background()
This really should be a context.TODO(), same same, but here we are expecting context to be wired through eventually.

2021-05-26 23:45 UTC, wallyworld requested changes
Please fix import before landing

2021-05-26 23:45 UTC, wallyworld commented on provider/gce/environ.go
> +	"github.com/juju/utils"
Should be utils/v2

2021-05-28 16:13 UTC, SimonRichardson commented
@wallyworld can you re-look, you're blocking a merge.

2021-05-30 23:55 UTC, hpidcock commented
$$merge$$

2021-05-31 00:23 UTC, merged