state: Add UserConnections to the all watcher
juju/juju pull request #13083
Opened 2021-06-16 11:19 UTC by mhilton

Add all watcher events for notifying on user connections. This implements
the feature requested in https://bugs.launchpad.net/juju/+bug/1929524.

## Checklist

 - [ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed
 - [ ] Comments answer the question of why design decisions were made

## QA steps

 1. Create a controller with this code version.
 2. Connect a client that calls `WatchAllModels` on the `Controller` facade and displays the results.
 3. Connect to a model on the controller (juju status)
 4. Verify the event stream includes a userConnection event with the connection time around step 3.

## Documentation changes

This adds a new event type into the AllWatcher event stream. The "userConnection" events will be fired every time a user connects to a model.

## Bug reference

- https://bugs.launchpad.net/juju/+bug/1929524

2021-06-16 16:25 UTC, SimonRichardson commented on core/multiwatcher/types.go
> +	UserConnectionKind    = "user-connection"
Can we be consistent here and do `userConnection`?

2021-06-16 16:34 UTC, SimonRichardson commented
We'll have to ensure that pylibjuju can also support this in case it starts showing up. The following change is just to add it to the [delta types](https://github.com/juju/python-libjuju/blob/master/juju/delta.py#L112-L123).

2021-06-17 07:57 UTC, alesstimec approved these changes

2021-06-17 07:57 UTC, alesstimec commented on apiserver/params/multiwatcher.go
> +type UserConnectionInfo struct {
godoc, please

2021-06-17 07:57 UTC, alesstimec commented on apiserver/params/multiwatcher.go
> +func (i *UserConnectionInfo) EntityId() EntityId {
godoc, please

2021-06-17 08:26 UTC, SimonRichardson requested changes
We need to retarget this against 2.9

2021-06-17 09:17 UTC, mhilton commented
I'm closing this to replace with #13086

2021-06-17 09:17 UTC, closed without merging