[2.9] Use CIDR-in-CIDR fallback when matching machine address CIDRs to subnet CIDRs
juju/juju pull request #13292
Opened 2021-08-31 17:22 UTC by achilleasa

Some providers (e.g. equinix) carve out a portion of an available subnet
and assign addresses off that to provisioned machines. For example, the
subnet pool might be a /25 and machines might get assigned a /31 carved
off the /25 range.

As a result, when executing network-get, Juju is unable to match the
subnet CIDRs reported by the machine agent to a subnet CIDR (the test
uses CIDR equality as its predicate) and therefore omits otherwise
usable private addresses from the reported ingress address list.

To fix this, SubnetInfos.GetByCIDR has been updated with a fallback: if
no match has been found using the equality check, a second match attempt
will be performed where we check whether the provided CIDR value (from
the machine address) is a subset of the subnet CIDRs that we know of.

Our definition of a subnet match is:
- Both CIDRs have the same host network
- The CIDR of the known subnet (as reported by the provider) defines a
mask with less one bits than the one we are trying to match against
(e.g. the subnet is a /24 and the input argument is a /31).

## QA steps

Deploy charmed kubernetes on equinix cloud and run `network-get` on the master nodes. The response should list a private IP at the top of the list followed by a FAN address.

2021-08-31 21:09 UTC, jameinel requested changes

2021-08-31 21:09 UTC, jameinel commented on core/network/subnet_test.go
> +	subs, err = s.GetByCIDR("10.10.10.0/31")
I think we need a check for "10.10.10.2/31" which should also be in the same parent subnet (if I understand what they are doing)

2021-09-01 07:28 UTC, achilleasa commented on core/network/subnet.go
> +		if subNet.IP.String() == parsedIpNetHost && subNetMaskBits <= parsedIpNetMaskBits {
That's a valid point. I have amended my PR (and added more comprehensive tests including the case you describe here) to use a more robust (but slower) approach where we calculate the IP range described by the CIDR and then check whether the two IPs are contained within the parent CIDR.

2021-09-01 16:36 UTC, jameinel approved these changes

2021-09-02 08:22 UTC, achilleasa commented
$$merge$$

2021-09-02 08:51 UTC, merged