Fix /etc/profile.d/juju-introspection.sh not being POSIX-shell compatible
juju/juju pull request #13299
Opened 2021-09-02 13:32 UTC by kot0dama

/etc/profile.d/juju-introspection.sh contains a few bash arrays, breaking POSIX shell compatibility and at least some packages post-installation as it is loaded as a profile script.

For example, on a model deployed with Juju 2.9.11, installing spamassassin yields a _Syntax error_ as spamassassin post-installation script attempts to run sa-update as debian-spamd user, having /bin/sh as shell.

The change includes variables name changes (and a comment) to avoid future updates breaking POSIX compatibility.
Feel free to update the comment to whatever you see fit.

## QA steps

* Check it builds properly
* Deploy a model with spamassassin installation (eg. charm cs:mailman3-core) and check it doesn't fail during SA install.

## Bug reference

Fixes https://bugs.launchpad.net/juju/+bug/1942430
Probable iteration of https://bugs.launchpad.net/juju/+bug/1770437

2021-09-02 14:20 UTC, jameinel commented
Sorry about the bot spam.
However, the code that you've defined for the POSIX mode is not actually compatible. At least in my testing I see:
```console
$ t () {
> arr=("$@")
> local -a args
> for i in "${arr[@]}"; do
>   args+=("unit=$i")
> done
> python3 -c 'import sys; print(sys.argv)' "${args[@]}"
> }
$ tt () {
> args=""
> for i in "$@"; do
>   args="$args unit=$i"
> done
> python3 -c 'import sys; print(sys.argv)' "$args"
> }
$ t a b
['-c', 'unit=a', 'unit=b']
$ tt a b
['-c', ' unit=a unit=b']
```

In our previous bash script you end up with 2 arguments with 'unit=X', while in the new form you end up with both an opening space, and a single argument that happens to have a space (and opens with an extra space as well)

I wonder if a better solution is not to try and make it Posix compliant, but just make it clear that it is `#!/bin/bash` rather than `#!/bin/sh`

2021-09-02 14:23 UTC, jameinel requested changes

2021-09-02 14:23 UTC, jameinel commented on worker/introspection/script.go
> +  juju_agent --post units action=stop "$args"
This doesn't actually have the same semantic.
However, maybe if we just avoid the "" around $args. It does look like:
```
$ tt () { args=""; for i in "$@"; do   args="$args unit=$i"; done; python3 -c 'import sys; print(sys.argv)' $args; }
$ tt a b
['-c', 'unit=a', 'unit=b']
```
Looks more like what we want to happen.

2021-09-02 14:23 UTC, jameinel commented on worker/introspection/script.go
> +  juju_agent --post units action=start "$args"
same here

2021-09-02 14:40 UTC, kot0dama commented
I see, indeed you're right removing the quotes around $args fixes it.
 
> I wonder if a better solution is not to try and make it Posix compliant, but just make it clear that it is `#!/bin/bash` rather than `#!/bin/sh`

About this, that won't cut it as it is not executed but source-d by the shell of the user, so every file in /etc/profile.d/ must be POSIX compatible. Another solution would be to add this:
```
# Not bash or zsh?
[ -n "${BASH_VERSION:-}" -o -n "${ZSH_VERSION:-}" ] || return 0
```

Anyways, I'll fix the quote issue and force push again.

2021-09-02 14:49 UTC, kot0dama commented
Here it is, let me know if that's better.
Thank you

2021-09-03 14:38 UTC, jameinel approved these changes

2021-09-03 14:38 UTC, jameinel commented
$$merge$$

2021-09-03 14:39 UTC, jameinel commented
I accidentally submitted it for merge before seeing that it was targeting Develop rather than the 2.9 branch. If it doesn't go through, I would appreciate if you would rebase targeting 2.9 and update the target of your PR, but otherwise we can backport this ourselves. Thank you for the POSIX fixes.

2021-09-03 15:05 UTC, merged