Re-deploying bundles with local charms
juju/juju pull request #13455
Opened 2021-10-27 23:26 UTC by cderici

### Description

#### Problem

Re-deploying a local bundle, with an application from a local charm results in an error like:

`ERROR cannot deploy bundle: cannot deploy local charm at "/home/caner/work/cderici/tmp/somecharm": file does not exist`

where `somecharm` is the name of charm for the app, not the local bundle file.

Here's the bug reference  : https://bugs.launchpad.net/juju/+bug/1942937

Juju's previous behavior for this (e.g. when it deploys a bundle that has an app -on a local charm- which is already on the model) was to ignore the charm by replacing the charm URL on the (to be deployed) bundle spec with charm's local URL in the model and have `getChanges` to return `no change` for this[**]. This seems to be wrong for multiple reasons, one being that it generates a path that doesn't exists (which is the main trigger for the error above), and secondly it's impossible to generate that path because we no longer have the filename information from which the initial charm was deployed in the first place.

[**] The comments in the code also states `We don't upgrade local charms as part of a bundle deploy`.

#### Solution

We change this behavior and treat deploying bundles that have local charms as refreshes on the charms, so we resolve the local charm and re-upload it.

## QA steps

Let's say you have a `bundle.yaml` with the following with a local `test.charm` with an application `foo`:

```yaml
bundle: kubernetes
applications:
  an-app:
    charm: ./test.charm
    scale: 1
```

```sh
$ juju deploy ./bundle.yaml
Executing changes:
- upload charm <path>/test.charm for series focal with architecture=amd64
- deploy application foo on focal
Deploy of bundle completed.
```

The second run should produce the following instead of the error above:

```sh
$ juju deploy ./bundle.yaml
Executing changes:
- upload charm <path>/test.charm for series focal with architecture=amd64
- upgrade hello-kubeconusing charm ./test.charm for series focal
- Deploy of bundle completed.
```

### Notes & Discussion

As referenced in the description, this PR attempts to solve https://bugs.launchpad.net/juju/+bug/1942937

This also removes a map that's being filled with application names but never seems to be used anywhere.

This also exposes a problem with URLs, where we write to the DB something like `local:appname-0` for a local charm URL as well, which is not a correct locator for a local charm (not a path, like `./../../../filename.charm`). This is a problem because `juju migrate` and `juju export-bundle` should be using that path to resolve a local charm.

2021-11-01 09:41 UTC, SimonRichardson requested changes
Let me think about this one.

2021-11-01 10:02 UTC, SimonRichardson requested changes
Is the idea to never update local charms from a bundle. The current self-imposed limitation is to prevent that, as originally it was difficult to know if an update to a local charm was available. This is done via the revision file/version file, so it's possible to register a change for juju to spot.

The only option for bundles with local charms is then to do `juju refresh`. I'm not sure that's a nice UX.

The real fix here is to bottom out the idea of getting the name from the `metadata.yaml` and using that to match the charm for local charms (charm URL becomes `local:<name>`) and not the path. As paths can leak sensitive information and are not consistent between deployments for users.

2022-01-25 09:17 UTC, SimonRichardson commented
Closing this because of no activity, please reopen if you want to move this forward.

2022-01-25 09:17 UTC, closed without merging

2022-01-25 12:05 UTC, heitorPB commented
> Closing this because of no activity, please reopen if you want to move this forward.

Is there any plan to fix this bug with a different approach?