[JUJU-416] Consistantly use juju/retry to handle retries 4 (worker/apicaller/*)
juju/juju pull request #13628
Opened 2022-01-18 13:09 UTC by jack-w-shaw

Throughout Juju we have inconsistent ways of performing retries. Standardise all retry code to the repository github.com/juju/retry.

Replace occurrences of this old method of retries from the worker/apicaller/ directory

## Checklist

 - ~[ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - ~[ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed~
 - [ ] Comments answer the question of why design decisions were made

## QA steps

```sh
make static-analysis
go test github.com/juju/juju/worker/apicaller
```

## Documentation changes

No documentation changes required

## Bug reference

https://bugs.launchpad.net/juju/+bug/1611427/

2022-01-24 14:11 UTC, manadart requested changes
Needs a small fix.

2022-01-24 14:11 UTC, manadart commented on worker/apicaller/connect.go
> +			if params.IsCodeNotProvisioned(err) {
This isn't quite right. 

Have a look at the `IsFatalError` member of retry `CallArgs`. This should be used to inform that a `NotProvisioned` error is not fatal, but others are.

Then we want to assign the retry result to `err` on line 153.

2022-01-25 14:03 UTC, manadart approved these changes
Looks good. Bootstrapped and deployed some workloads:
```
Unit           Workload  Agent  Machine  Public address  Ports                                    Message
mongodb/0      active    idle   3        10.161.87.178   27017/tcp,27019/tcp,27021/tcp,28017/tcp  Unit is ready as SECONDARY
mongodb/1*     active    idle   4        10.161.87.132   27017/tcp,27019/tcp,27021/tcp,28017/tcp  Unit is ready as PRIMARY
mongodb/2      active    idle   5        10.161.87.117   27017/tcp,27019/tcp,27021/tcp,28017/tcp  Unit is ready as SECONDARY
postgresql/0*  active    idle   6        10.161.87.4     5432/tcp                                 Live master (12.9)
postgresql/1   active    idle   7        10.161.87.200   5432/tcp                                 Live secondary (12.9)
postgresql/2   active    idle   8        10.161.87.161   5432/tcp                                 Live secondary (12.9)
ubuntu/0*      active    idle   0        10.161.87.216
ubuntu/1       active    idle   1        10.161.87.20
ubuntu/2       active    idle   2        10.161.87.141
```

2022-01-25 14:33 UTC, jack-w-shaw commented
$$merge$$

2022-01-25 15:09 UTC, merged