[JUJU-416] Consistantly use juju/retry to handle retries 3 (state/*)
juju/juju pull request #13624
Opened 2022-01-17 14:49 UTC by jack-w-shaw

Throughout Juju we have inconsistent ways of performing retries. Standardise all retry code to the repository github.com/juju/retry.

Completely drop the function where this old retries strategy was used. Can do this since it wasn't in use anymore

## Checklist

 - ~[ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - ~[ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed~
 - [x] Comments answer the question of why design decisions were made

## QA steps

Run on a linux and windows machine:
```sh
make static-analysis
go test github.com/juju/juju/state/
```

## Documentation changes

No documentation changes required

## Bug reference

https://bugs.launchpad.net/juju/+bug/1611427/

2022-01-17 15:04 UTC, SimonRichardson requested changes

2022-01-17 15:04 UTC, SimonRichardson commented on state/backups/restore.go
> +	err = retry.Call(retry.CallArgs{
Can we split this out to a strategy pattern, that you've set up in the previous PRs.

2022-01-24 14:05 UTC, SimonRichardson approved these changes

2022-01-24 15:50 UTC, jack-w-shaw commented
$$merge$$

2022-01-24 16:28 UTC, merged