add firewaller support to Equinix Metal provider
juju/juju pull request #13695
Opened 2022-02-02 17:43 UTC by displague

add firewaller support to Equinix Metal provider 

Continues #13552 

Fixes https://bugs.launchpad.net/juju/+bug/1940520

## Checklist

 - [ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed
 - [ ] Comments answer the question of why design decisions were made

## QA steps

*Please replace with how we can verify that the change works.*

```sh
QA steps here
```

## Documentation changes

*Please replace with any notes about how it affects current user workflow, CLI, or API.*

## Bug reference

*Please add a link to any bugs that this change is related to, e.g., https://bugs.launchpad.net/juju/+bug/9876543*

2022-02-03 11:13 UTC, achilleasa commented
On a _quick_ glance, the logic seems correct. 

However what is missing is some extra cloud-init scripts to lock down access to the machines that Juju provisions. In particular, for **non-controller** instances, you would need to add iptables rules to block INGRESS traffic on the NIC that has been assigned a public IP but allow EGRESS (outgoing, established, and most importantly, **related** sessions).

This should allow the machine to reach the internet so it can download the resources it needs but would otherwise prevent incoming connections unless you `juju expose` an application in which case the firewaller code from this PR would be invoked to update the ingress rules.

2022-02-03 11:15 UTC, achilleasa commented
@manadart can you please track this PR? It still needs some work before it can correctly address the issue referenced in the attached bug.

2022-02-03 11:18 UTC, achilleasa commented
@displague Can you please update the PR description and add some commands that folks can use as QA steps for the PR? 

For example, a nice scenario for testing would be: bootstrap, deploy  a charm such as redis and verify that it's port is not accessible via the public IP assigned to the box. Then, `juju expose redis` (also try the `--to-cidr` argument to make sure it works) and check that the port becomes accessible. Finally, un-expose the app and verify that once more the port is not accessible.

2022-05-11 07:45 UTC, manadart commented
@displague Happy to push this through when Achilleas' comments above are addressed. 

Otherwise, if this is no longer the preferred solution, we can close it.

2022-07-21 17:27 UTC, manadart requested changes
I see where this is failing now.

Upon running `juju expose`, this log line can be seen:
```
controller-0: 19:16:06 INFO juju.worker.firewaller flushInstancePorts called on an instance of type *equinix.equinixDevice which doesn't support firewall.
```
You need to to modify the instance to implement `InstanceFirewaller` from _environs/instances/instance.go_.

The instance configurator doesn't work as an environ firewaller. See https://github.com/juju/juju/pull/10288 for an example of adding it to the OCI provider.

2022-07-23 03:55 UTC, displague commented
@manadart What commands are you using (or where are you looking) to see that log message?


Also, I tried the `juju deploy '~juju-qa/network-health'` example from OCI PR, but this want not found.

2022-07-25 09:21 UTC, manadart commented
Yes, that patch dates from before Charmstore was superseded by Charmhub. You should be able to show it up by exposing any application.

2022-07-25 09:25 UTC, manadart reviewed
Almost there. Some dead code to remove.

2022-07-25 09:25 UTC, manadart commented on provider/equinix/firewaller.go
> +// DeleteGroups implements OpenstackFirewaller interface.
We want to delete from here down in this file.

2022-08-02 16:50 UTC, manadart approved these changes
QA'd just using an app directly on the controller.

I can see the ingress rules applied:
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  <my IP>  anywhere             tcp dpt:x11 /* juju ingress */
```

2022-08-02 16:50 UTC, manadart commented
/merge

2022-08-02 17:24 UTC, merged

2022-08-05 03:46 UTC, displague commented
@manadart I ran my test steps again on 2.9 and I see what you saw. 

```
$ iptables -L -t filter 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  <my-ip>  anywhere             tcp dpt:http /* juju ingress */
...
```

The default input policy is ACCEPT, however, so with the expose or unexpose, I'm still able to access the service.
Should additional rules be inserted to change the default policy to DROP? Does iptables-persistent need to be installed?