Fix clashing of user vs juju/system action keys
juju/juju pull request #13748
Opened 2022-02-15 20:01 UTC by rwcarlsen

When charms set action results/keys via action-set, it is possible that the charm sets "special" action keys (i.e. stdout, stderr) via the key=val args.  This caused a race condition between juju collecting stdout/stderr from running the action hook (i.e.  worker/uniter/runner runner.updateActionResults) and the hook's call to "action-set [key=val]..." resulting in one of the action-set key+val or the hook stdout winning and clobbering the other in the controller.  It also caused other unexpected behavior if the charm set the stdout result key to the empty string (the "stdout" key would be omitted from results entirely) or showing the content of the "stdout" result key under the capitalized "Stdout" key in the final client results printout, etc.

To resolve all these issues this PR adds a check to ensure that none of the keys being set via action-set are in a reserved set that juju uses for special purposes under the hood and errors out accordingly.

This was originally reported and investigated via https://github.com/canonical/operator/issues/689.

## QA steps

I added a unit test:

```
cd worker/uniter/runner/jujuc
go test
```

Canonical/operator#689 details how the problem was initially encountered - basically calling the hook tool like this `action-set stdout=42` was enough to trigger unexpected behavior, but should now just cause an error to be emitted with this PR.  More specifically, an ops charm with an action that has this code will cause clobbering - and we'd prefer an error (i.e. this PR/patch):

```
    def _on_foo_action(self, event)
        event.set_results({'stdout': 'forty-two'})
        print(42)
```
It is a race between:

*  the runner recording `42` from the hook's stdout and
*  the action-set called by the ops framework using event.set_results content - `forty-two`.  

This patch causes an error to be emitted when running such an action instead of the race/clobbering.

## Documentation changes

Included.

2022-02-15 21:06 UTC, hmlanigan commented
@rwcarlsen thank you for your patch.  I've enabled the normal PR checks to run, please let us know if you're unable to view the results.  

Please add qa steps for a user to run, verifying your change.

2022-02-21 12:08 UTC, SimonRichardson approved these changes

2022-02-21 12:08 UTC, SimonRichardson requested changes
Actually, I just spotted this is targetting develop. Can we re-target 2.9 branch?

2022-03-01 16:48 UTC, rwcarlsen commented
Ping - could we get the ci/tests running again?

2022-03-01 18:14 UTC, SimonRichardson approved these changes

2022-03-01 18:14 UTC, SimonRichardson commented
!!build!!

2022-03-03 20:35 UTC, rwcarlsen commented
still not running :/

2022-03-09 17:35 UTC, SimonRichardson commented
$$merge$$

2022-03-09 18:09 UTC, merged