[JUJU-656] Fix microk8s gh actions
juju/juju pull request #13772
Opened 2022-02-21 17:11 UTC by jack-w-shaw

Uses a weird hacky behavior, to be more thoroughly investigated and
'fixed' soon. Temporarily use to fix CI

More detail as to why this needs to be done can be found in the launchpad reference

## Checklist

 - ~[ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - ~[ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed~
 - [ ] Comments answer the question of why design decisions were made

## QA steps

Run microk8s upgrade action to completion. Checking the test result is valid as well

## Documentation changes

N/A

## Bug reference

https://bugs.launchpad.net/juju/+bug/1961614

2022-02-23 20:36 UTC, wallyworld reviewed
This seems ok to get some level of upgrade testing but ideally we'd fix the underlying issue

2022-03-14 21:19 UTC, wallyworld requested changes
Test fails

Run set -euxo pipefail
+ sg microk8s
ERROR constructing controller config: docker image path "'{\"repository\": \"10.152.183.69:5000/test-repo\", \"serveraddress\": \"[https://10.152.183.69:5000/\](https://10.152.183.69:5000//)"}'": invalid reference format
Error: Process completed with exit code 1.

2022-03-16 09:26 UTC, wallyworld approved these changes

2022-03-16 10:17 UTC, jack-w-shaw commented
$$merge$$

2022-03-16 10:52 UTC, merged