Fix occasional race condition in worker/upgradedatabase/worker_test.go
juju/juju pull request #13905
Opened 2022-03-29 11:49 UTC by jack-w-shaw

Do this by increasing the timeout

Example of a failure is here: https://jenkins.juju.canonical.com/view/ci-run/job/Unit-RunUnitTests-race-amd64/1186/

## Checklist

 - [ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed
 - [ ] Comments answer the question of why design decisions were made

## QA steps

Run unit tests in Jenkins multiple times to be confident the test now succeeds

## Documentation changes

N/A

## Bug reference

N/A

2022-03-30 04:52 UTC, wallyworld reviewed
Thanks for fixing this. Though I'm not sure it's the "right" fix. The test suite fully uses mocks so should be fast to run. `LongWait` should be more than enough time to wait for some mocked methods to be called.

2022-03-30 09:19 UTC, jack-w-shaw commented
I'm not convinced either, but a race condition like this is the only thing I can see being a cause. Unless there's some other rare race condition I haven't spotted yet?

2022-03-31 07:58 UTC, manadart requested changes
If you look at this carefully you'll see that watching for primary changes introduced a new `clock.After` call that is implicitly satisfied by `s.clock.EXPECT().After(gomock.Any()).Return(timeout).AnyTimes()`.

This test needs needs tightening for expectations. I would.
- See to the parameter detection for the `After` expectation.
- Replace `AnyTimes` with `MinTimes(1)` where appropriate.
- Just close the `finished` channel instead of writing to it.

2022-03-31 11:48 UTC, jack-w-shaw commented
Good spot Joe. I had noticed myself that the `EXPECT` line there catches both the main timeout, and the check primary loop, but hadn't put together quite how error prone that could be with both these timers pulling from the same channel.

Will fix now, and make the other clean ups you've pointed out

2022-03-31 12:34 UTC, manadart approved these changes
I think we'll find that this is the fix. Please update the description before landing.

2022-03-31 12:34 UTC, manadart commented on worker/upgradedatabase/worker_test.go
> +	neverTimeout := make(chan time.Time, 1)
Nit: don't need a buffer.

2022-03-31 14:26 UTC, jack-w-shaw commented
$$merge$$

2022-03-31 21:04 UTC, wallyworld commented
merge job looks like it failed due to an issue in suite teardown, even though individual tests passed.
This will need fixing before landing.

2022-04-01 10:00 UTC, jack-w-shaw commented
I suspect my flyby bug fix resolves this

2022-04-01 12:28 UTC, jack-w-shaw commented
$$merge$$

2022-04-01 13:03 UTC, merged