[JUJU-880] Pick right channel from CharmHub info response based on release date
juju/juju pull request #13951
Opened 2022-04-08 22:41 UTC by cderici

When picking the latest channel info for each `track/risk`, `juju info` picks the last element from the channel map (that we're getting from the CharmHub's `info` endpoint). This PR patches that picking process, by picking the one with the latest release date.

## QA steps

QA'ing this particular PR can be done by checking the revision number, so for

`juju info neutron-api --channel xena/edge --series focal` should look like 

```channels: |
  xena/stable:     –
  xena/candidate:  –
  xena/beta:       –
  xena/edge:       522  2022-04-01  (522)  794kB
```

(that revision # was incorrectly 501 before this change, as it is reported in the LP bug referenced below)

and 

`juju info neutron-api --channel xena/edge --series bionic` should look like

```channels: |
  xena/stable:     –
  xena/candidate:  –
  xena/beta:       –
  xena/edge:       501  2022-03-04  (501)  483kB
```

Also a unit test is added for this as well, so 

```sh
cd juju/cmd/juju/charmhub && go test -gocheck.vv -gocheck.f TestFilterChannels
```
should pass.

Properly testing this (and keep testing it as a part of integration tests) requires either using a mock charm, or `juju-qa-test`. Deferring to the further discussions here to iterate over.

## Bug reference

https://bugs.launchpad.net/juju/+bug/1967850

2022-04-11 09:59 UTC, juanmanuel-tirado requested changes

2022-04-11 09:59 UTC, juanmanuel-tirado commented on cmd/juju/charmhub/convert.go
> +			currentChReleasedAt, _ := time.Parse(time.RFC3339, currentCh.ReleasedAt)
Catch error from `time.Parse` before continuing.

2022-04-11 17:19 UTC, cderici commented
> It looks like the code works when you specify a series. However if you do not, you still don't get the latest.

Oh I thought I tested that, I'll take another look, thanks for trying it out! :+1:

2022-04-12 16:22 UTC, cderici commented
> It looks like the code works when you specify a series. However if you do not, you still don't get the latest.

I still get the correct `xena/edge:       522  2022-04-01  (522)  794kB` from `juju info neutron-api --channel xena/edge` with this change, @hmlanigan, not sure why're you getting the wrong revision, can you try again whenever you can? Thanks!

2022-04-13 19:11 UTC, hmlanigan commented
@cderici pulled down the code clean and now get the expected results.

2022-04-13 19:15 UTC, hmlanigan approved these changes
LGTM

2022-04-14 19:33 UTC, cderici commented
!!build!!

2022-04-15 15:46 UTC, cderici commented
$$merge$$

2022-04-15 17:14 UTC, cderici commented
$$merge$$

2022-04-15 20:04 UTC, cderici commented
$$merge$$

2022-04-15 20:37 UTC, merged