Merge 2.9 into develop
juju/juju pull request #14017
Opened 2022-05-11 14:35 UTC by manadart

Merge from 2.9 to bring forward:
- #14007 from wallyworld/update-golang-deps
- #14013 from hmlanigan/show-controller-panic
- #14012 from hmlanigan/remove-unit-subordinate
- #13998 from turrisxyz/setup-permissions
- #14011 from ycliuhw/update-ck-overlay
- #14010 from tlm/juju-jenkins-tests
- #14004 from tlm/juju-jenkins-tests
- #14003 from manadart/2.9-close-unit-loggers
- #14001 from jack-w-shaw/JUJU-1050_show_unit_life
- #13890 from juju/dependabot/github_actions/actions/upload-artifact-3
- #14000 from wallyworld/use-go1.18
- #13999 from tlm/juju-jenkins-tests
- #13991 from ycliuhw/fix/lp1968643
- #13997 from tlm/cross-compile
- #13931 from arnodel/juju-885-remove-modelaccess-connection-iface-method
- #13992 from jack-w-shaw/JUJU-1034_reduce_over_verbose_logging_network
- #13993 from hmlanigan/fix-intermittent-fail-testenqueuedoperation
- #13990 from wallyworld/handle-azure-quota-errors
- #13989 from benhoyt/start-worker-if-dead
- #13987 from hpidcock/filter-test-packages

Conflicts:
- cmd/juju/controller/showcontroller.go
- go.mod
- go.sum
- provider/azure/environ_test.go

2022-05-11 20:24 UTC, hmlanigan commented
@manadart I'm unable to change the target branch from 2.9 to develop for you.  Looking to review.

2022-05-11 20:55 UTC, hmlanigan approved these changes
I reviewed the showcontroller.go conflict, small edit. Ran go mod tidy. Hopefully the unit tests will show if there any issues with the azure test change noted as conflicts,

2022-05-11 20:57 UTC, hmlanigan commented
$$merge$$

2022-05-11 22:47 UTC, tlm approved these changes
lgtm happy that my changes are represented correctly.

2022-05-11 23:00 UTC, barrettj12 commented
Feel free to ignore the Smoke, Snapcraft, Upgrade and macOS client tests - I'm [working on fixing these](https://github.com/juju/juju/pull/14006). The Ubuntu client tests and Jenkins failures are probably cause for concern though.

2022-05-11 23:53 UTC, wallyworld requested changes

2022-05-11 23:53 UTC, wallyworld commented on provider/azure/environ_test.go
> +func (s *environSuite) TestStartInstanceCommonDeploymentStorageAccount(c *gc.C) {
delete me - this is gone in 3.0

2022-05-11 23:53 UTC, wallyworld commented on provider/azure/environ_test.go
> +func (s *environSuite) TestStartInstanceCommonDeploymentWithStorageAccountAndAvailabilitySetName(c *gc.C) {
delete me - this is gone in 3.0

2022-05-11 23:58 UTC, wallyworld commented
Also, the `TestManifoldsDependenciesCAAS` error is because the `restore-watcher` worker is gone in 3.0 so somehow that has leaked back in with this PR

2022-05-12 00:16 UTC, wallyworld requested changes

2022-05-12 00:16 UTC, wallyworld commented on cmd/jujud/agent/machine/manifolds_test.go
> +		"restore-watcher",
delete me - gone in 3.0

2022-05-12 00:16 UTC, wallyworld commented on cmd/jujud/agent/machine/manifolds_test.go
> +		"restore-watcher",
delete me - gone in 3.0

2022-05-12 00:16 UTC, wallyworld commented on cmd/jujud/agent/machine/manifolds_test.go
> +	},
delete me - gone in 3.0

2022-05-12 06:46 UTC, wallyworld approved these changes

2022-05-12 10:44 UTC, ycliuhw approved these changes
My changes are correct, thank you

2022-05-16 07:38 UTC, manadart commented
$$merge$$

2022-05-16 08:07 UTC, merged