[draft] remove Windows stuff
juju/juju pull request #14093
Opened 2022-05-30 06:53 UTC by barrettj12

2022-05-30 07:59 UTC, juanmanuel-tirado commented
I love this branch :)

I added the "do-not-merge" label. Feel free to remove it.

2022-06-17 06:57 UTC, barrettj12 commented
So something's not right. I removed the agent names from `juju/names/names_windows.go`, and now when you try
```
GOOS=windows go build github.com/juju/juju/cmd/juju
```
it complains about
```
# github.com/juju/juju/agent/tools
agent/tools/symlinks.go:43:44: undefined: names.Jujuc
agent/tools/symlinks.go:46:45: undefined: names.Jujud
```
This looks like a case of bad dependency - the client is importing `X` from package `Y`, and somewhere else package `Y` imports (something which imports) `agent/tools`. I can't find the path from `cmd/juju` to `agent/tools` though.

2022-06-20 01:14 UTC, barrettj12 commented
Found it:
```
github.com/juju/juju/cmd/juju
github.com/juju/juju/cmd/juju/commands
github.com/juju/juju/environs
github.com/juju/juju/cloudconfig/instancecfg
github.com/juju/juju/agent/tools
```
... this looks like a mess.

2022-06-22 06:13 UTC, wallyworld requested changes
Just a few small things, the main issue seems to be where we had logic for !windows that has been removed by mistake.
I may have missed it, but we also want logic (if not there already) to prevent Windows charms from being deployed - short circuit at deploy time. Also need to prevent `add-machine --series=win2012` and fail early (if not already done).

2022-06-22 06:13 UTC, wallyworld commented on state/application_test.go
> -func (s *ApplicationSuite) TestClientApplicationSetCharmWrongOS(c *gc.C) {
Use centos or something but need to keep the test

2022-06-22 06:13 UTC, wallyworld commented on worker/uniter/runner/args.go
>  func hookCommand(hook string) []string {
can look to remove this fucntion now, it doesn't add anything

2022-06-22 06:13 UTC, wallyworld commented on worker/uniter/runner/jujuc/util_test.go
>  func cmdString(cmd string) string {
delete this function

2022-06-22 07:44 UTC, barrettj12 commented on cmd/juju/ssh/debughooks_test.go
> -		c.Skip("bug 1403084: Skipping on windows for now")
It's already closed

2022-06-22 07:55 UTC, barrettj12 commented on juju/names/names.go
> -// +build !windows
Nah the binary names are needed on Windows for the client to compile (because of bad dependencies). This is the issue I was talking about earlier

2022-06-23 04:54 UTC, tlm commented on cmd/jujud/reboot/reboot.go
> +	tpl := `#!/bin/bash
We're setting the shebang line here to bash but we're executing it with bourne shell below. Should be a little more explicit.

2022-06-23 04:54 UTC, tlm commented on cmd/jujud/reboot/reboot.go
> +	err = os.Chmod(name, 0755)
We're executing the file the actual interpreter so we don't need this script to be executable in fact it's probably better from a security stand point.

2022-06-23 04:54 UTC, tlm commented on cmd/jujud/run/run_test.go
> +	socket.Address = fmt.Sprintf("%s/run.socket", agentDir)
This should be path.Join()

2022-06-23 04:54 UTC, tlm commented on common/sender/sender.go
> +// Copyright 2015 Canonical Ltd.
Update copyright year

2022-06-23 04:54 UTC, tlm commented on environs/imagemetadata/urls_test.go
> +		expected:    "file:///home/foo/images",
Don't think this should have `/images` on the end.

2022-06-23 04:54 UTC, tlm commented on environs/tools/urls_test.go
> +		expected:    "file:///home/foo/tools",
Think this shouldn't have /tools on it.

2022-06-26 08:06 UTC, tlm commented
@wallyworld want to take another look over this before we look at hitting the merge button

2022-06-27 00:10 UTC, wallyworld approved these changes

2022-06-27 04:29 UTC, barrettj12 commented
/merge

2022-06-27 06:07 UTC, barrettj12 commented
/merge

2022-06-27 06:38 UTC, merged