[JUJU-1441]Status_panic_when_status_color_is_unknown
juju/juju pull request #14302
Opened 2022-07-12 21:33 UTC by basebandit

This PR fixes a bug introduced by PR [14293](https://github.com/juju/juju/pull/14293). for `juju status --format=summary`

## Checklist

 - ~[ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - ~[ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR~
 - ~[ ] Added or updated [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) related to packages changed~
 - ~[ ] Comments answer the question of why design decisions were made~

## QA steps
In a separate terminal run

```sh
watch --color juju status --format=summary --color
```
In another run
```sh
juju deploy postgresql
```

2022-07-12 21:47 UTC, jameinel requested changes
needs a unit test that `StatusColor` doesn't fail when passed an unknown status.

2022-07-13 07:46 UTC, basebandit commented
/merge

2022-07-18 14:09 UTC, jameinel approved these changes

2022-07-18 14:48 UTC, merged

2022-07-25 09:47 UTC, manadart commented on cmd/output/package_test.go
> +package output_test
Prefer putting _package_test.go_ files in the logic's package (`output` in this case).