[JUJU-1700] Added --viddy flag to watch status changes via Viddy tool
juju/juju pull request #14528
Opened 2022-08-29 12:14 UTC by anvial

This PR adds `--viddy` flag to `juju status` command. This flag allows watching `juju status` changes via the Viddy (https://github.com/juju/viddy) tool. This flag cannot be mixed with the `--watch` flag.

PS: If we liked the Viddy experience, we could make Viddy a standard `--watch` flag behavior in the future.

## Checklist

- [ ] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [ ] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

```sh
juju bootstrap lxd lxd
juju deploy tiny-bash

juju status --viddy 1s
juju status --viddy 5s
juju status --viddy 1s --no-color

juju status --viddy 1s --watch 2s
```

## Documentation changes

TBD

2022-08-29 12:36 UTC, jnsgruk commented
Feels like doing both is just bloat - can we just make viddy the default, or is it dependant on an external binary?

2022-08-29 16:33 UTC, anvial commented
> Feels like doing both is just bloat - can we just make viddy the default, or is it dependant on an external binary?

No, there is no problem with doing viddy the default. 
We use our viddy fork that provides Viddy as an importable package (so there is no dependency on external binary).

2022-08-29 17:38 UTC, anvial commented
Now Viddy is the default for `juju status --watch`

2022-09-20 08:35 UTC, manadart requested changes
Some minor things.

2022-09-20 08:35 UTC, manadart commented on cmd/juju/status/status.go
> +	viddy time.Duration
This is not used and needs deleting.

2022-09-20 08:35 UTC, manadart commented on cmd/juju/status/status.go
> +		// Prepare Viddy args
This comment is not required.

2022-09-20 08:35 UTC, manadart commented on cmd/juju/status/status.go
> +func (c *statusCommand) statusArgsWithoutWatchFlag(args []string) ([]string, string) {
You already have the watch value in `c.watch` no need to return it. You only need the stripped args.

2022-09-20 09:14 UTC, manadart commented
After running this, I have a weird issue with uxterm. My cursor has disappeared...

2022-09-23 10:57 UTC, manadart approved these changes

2022-09-23 10:59 UTC, anvial commented
/merge

2022-09-26 07:55 UTC, anvial commented
/merge

2022-09-26 11:24 UTC, anvial commented
/merge

2022-09-26 12:15 UTC, merged