[JUJU-1761] Developed the bash-based change-user-password test using the expect tool
juju/juju pull request #14626
Opened 2022-09-19 13:59 UTC by anvial

This PR adds the change-user-password test, which is an interactive command. This test uses expect tool and generates expect scripts. 

The `expect_that` function is introduced, its implementation inspired by the `wait_for` function. This function can be part of `includes` tools.

PS:
please, use the apt version of the `expect` tool to avoid access problems.
```
sudo apt install expect
```

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made

## QA steps

```sh
cd tests
./main.sh -v -p lxd user run_user_change_password
```

2022-09-19 21:03 UTC, hmlanigan requested changes
Check for dependencies needs to be updated to include `expect`: https://github.com/juju/juju/blob/cde164f1124781f102e3d71bba88547043a1812a/tests/main.sh#L233

Running QA step resulted in:
couldn't read file "/home/heather/work-test/src/github.com/juju/juju/tests/tmp.q7t/juju-change-user-password.exp": permission denied

2022-09-20 09:12 UTC, anvial commented on tests/suites/user/login_password.sh
> +# wait_for <command> <expect_script> [<timeout>]
fixed

Also, there is a suggestion to rename the command from `expect_command` to `expect_that`. That will make this command more understandable to developers and closer to `wait_for`.

2022-09-20 10:36 UTC, anvial commented
@hmlanigan ,

Looks like the problem is in the snap version of the `expect` tool. 

so 

```
sudo snap remove expect
sudo apt install expect
```

should help.

2022-09-21 13:01 UTC, hmlanigan approved these changes
A small nit based on issues encountered with QA. ow LGTM

2022-09-23 09:12 UTC, anvial commented
Discussed with Joe the question of additional messaging about `apt` version of the `expect` tool. Looks like we shouldn't worry about specifically detecting apt. The `expect` snap is used only like a "pipe tool", so it's no like someone is likely to satisfy a check with the snap-installed version accidentally.

2022-09-23 10:16 UTC, anvial commented
/build

2022-09-26 09:43 UTC, merged