[JUJU-2339] Remove macaroons for no cs on juju
juju/juju pull request #14996
Opened 2022-12-13 23:45 UTC by cderici

Remove the CharmStore macaroons as a side effort to retiring CharmStore from the client entirely. 

Relates to PRs such as #14968, #14985 (<- I think this PR has a conflict with this one)

## QA Steps

As CharmStore charms are not supported, this doesn't change any behavior.

2022-12-14 19:32 UTC, hmlanigan requested changes

2022-12-14 19:32 UTC, hmlanigan commented on apiserver/facades/client/charms/client.go
> -func (a *API) AddCharmWithAuthorization(args params.AddCharmWithAuth) (params.CharmOriginResult, error) {
You need to rev the facade to version 6, and keep this method for version 5. juju 3.0.x clients use the method. The 3.0.x client should still be able to deploy charmhub charms to a 3.1 controller, and this method is used.

2022-12-14 19:32 UTC, hmlanigan commented on apiserver/facades/controller/firewaller/firewaller.go
> -func (f *FirewallerAPI) MacaroonForRelations(args params.Entities) (params.MacaroonResults, error) {
I think this is a different type of macaroon, not for charm store. It's related to CMR, which wouldn't be contacting the charm store. Should investigate this more.

2022-12-14 19:32 UTC, hmlanigan commented on state/charm.go
> -func (c *Charm) Macaroon() (macaroon.Slice, error) {
Add a charm to remove 
```
Macaroon     []byte `bson:"macaroon"`
```
from CharmDoc in state in 3.1

2022-12-15 20:49 UTC, hmlanigan reviewed
I think we can stop using a *httpbakery.Client, however that might be a piece for when we stop using the charmstore client in general.

2022-12-15 20:49 UTC, hmlanigan commented on cmd/juju/application/refresher/refresher.go
> -			Macaroon: csMac,
CharmID here is defined in refresher/interface.go, Macaroon can be removed from it now too

2022-12-15 20:49 UTC, hmlanigan commented on core/charm/repository/charmhub.go
>  	// TODO(achilleasa): pass macaroons to client when charmhub rolls out support for private charms.
remove todo

2022-12-15 20:49 UTC, hmlanigan commented on core/charm/repository/charmhub.go
> +
unrelated, couldn't select the lines for a pr comment - there is a TODO to be removed: lines 424-428

2022-12-15 20:49 UTC, hmlanigan commented on core/charm/repository/charmhub.go
> +	// TODO (cderici): This grouping below might not be necessary anymore
To answer the question, it looks like lines 390 to 419 can be deleted to me.

2022-12-15 20:49 UTC, hmlanigan commented on cmd/juju/application/store/store.go
>  // also handles the macaroon authorization process using the given csClient.
header comment requires updates to remove macaroon

2022-12-15 20:49 UTC, hmlanigan commented on cmd/juju/application/deployer/charm.go
> -		d.csMac,
csMac can also be removed from the deployCharm struct now, deployer/charm.go ln 42

2022-12-15 20:49 UTC, hmlanigan commented on cmd/juju/application/deployer/bundlehandler.go
> -		macaroons:            make(map[charm.URL]*macaroon.Macaroon),
remove from struct definition as well.

2022-12-15 20:49 UTC, hmlanigan commented on cmd/juju/application/store/interface.go
>  // CharmsAPI is functionality needed by the CharmAdapter from the Charms API.
The MacaroonGetter interface above be removed.

2022-12-15 20:49 UTC, hmlanigan commented on cmd/juju/application/deploy_test.go
>  		chID resources.CharmID,
deploy_test still imports macaroon.v2, so some references still exist.

2022-12-15 20:49 UTC, hmlanigan commented on apiserver/facades/client/charms/client.go
> -func (a *API) AddCharmWithAuthorization(args params.AddCharmWithAuth) (params.CharmOriginResult, error) {
No problem deploying a ch charm from a 3.0 client to a controller running this code.

2022-12-15 21:15 UTC, cderici commented on cmd/juju/application/store/store.go
> +		if resultOrigin, err = client.AddCharm(curl, origin, force); err != nil {
Yeah that's basically [eta-equivalent ](https://en.wiktionary.org/wiki/eta_conversion#English) to `AddCharm`, we can just use that instead :+1:

2023-01-03 20:11 UTC, hmlanigan commented on core/charm/repository/charmhub.go
>  func (c *CharmHubRepository) GetEssentialMetadata(reqs ...corecharm.MetadataRequest) ([]corecharm.EssentialMetadata, error) {
I believe you can delete lines 392 to and including 431. GetEssentialMetadata does batching which is no longer required as there are no macaroons to batch. getEssentialMetadataForBatch does the real work still required.

Then the TODO at 436 can be removed.

2023-01-03 20:11 UTC, hmlanigan commented on core/charm/repository/charmhub.go
>  	// TODO(achilleasa): pass macaroons to client when charmhub rolls out support for private charms.
todo still needs to be removed.

2023-01-04 21:17 UTC, hmlanigan commented on core/charm/downloader/downloader.go
> -		Macaroons:    macaroons,
remove Macaroons from the DownloadedCharm type definition

2023-01-05 18:58 UTC, hmlanigan approved these changes
LGTM. Removing functionality can be hard work!

2023-01-05 19:00 UTC, cderici commented
/merge

2023-01-05 19:27 UTC, merged