[JUJU-2449] Allow building locally without a LXC container
juju/juju pull request #15057
Opened 2023-01-13 17:02 UTC by SimonRichardson

In jenkins we have complete control over the whole machine, so it seems very wasteful to put the build script in a container. It also makes it REALLY hard to debug if it's in a nested container.

## Checklist

## QA steps

```sh
$ dqlite-build
```

2023-01-17 13:24 UTC, beliaev-maksim requested changes

2023-01-17 13:24 UTC, beliaev-maksim commented on .gitignore
> +dqlite-deps.tar.bz2
```suggestion
dqlite-deps.tar.bz2

```

2023-01-17 13:24 UTC, beliaev-maksim commented on scripts/dqlite/build-script.sh
> +tar cjvf juju-dqlite-static-lib-deps.tar.bz2 juju-dqlite-static-lib-deps
```suggestion
tar cjvf juju-dqlite-static-lib-deps.tar.bz2 juju-dqlite-static-lib-deps

```

2023-01-18 09:05 UTC, manadart reviewed
`make dqlite-build` works, but `make dqlite-local-build` results in:
```
make dqlite-local-build
DQLITE: Executing build script
bash: line 1: ./scripts/dqlite/build-script.sh: Permission denied
DQLITE: Placing lib archive
mv: cannot stat './scripts/dqlite/dqlite-deps.tar.bz2': No such file or directory
make: *** [scripts/dqlite/Makefile:65: dqlite-local-build] Error 1
```

2023-01-20 11:27 UTC, manadart approved these changes

2023-01-20 11:27 UTC, merged

2023-01-20 11:27 UTC, SimonRichardson commented
/merge