[JUJU-1844] Bash-based version of nw-deploy-bionic-aks-test
juju/juju pull request #15193
Opened 2023-02-16 09:43 UTC by anvial

This PR adds a bash-based version of the nw-deploy-bionic-aks-test.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made

## QA steps

```sh
cd tests ; ./main.sh -v deploy_caas run_deploy_aks
```

2023-02-16 09:45 UTC, SimonRichardson approved these changes

2023-02-16 13:08 UTC, jack-w-shaw requested changes
Static analysis is failing. There's a mix of tabs and spaces

2023-02-16 13:17 UTC, jack-w-shaw commented on tests/suites/deploy_caas/task.sh
> +  esac
I don't really think this integration test belongs here

We are always running a test in azure if the provider is 'k8s'. Ideally we would treat aks as it's own provider. This is particularly nasty given we bootstrap a controller inside of the unit test itself.

Creating a new aks provider will become necessary if we want any more integration tests, but it'll be a fairly substantial bit of work. My preference in the short term would be to extract this out into its own integration test. It's not nice that we have to bootstrap a controller in aks, successfully run the integration test, then tear down before we even start `test_desploy_charm` in it's own controller. Ideally each integration test suite would only require bootstrapping a single controller

2023-02-16 14:07 UTC, jack-w-shaw approved these changes
Approved, once some minor fixes have been made

2023-02-16 14:07 UTC, jack-w-shaw commented on tests/includes/controller.sh
> +  cloud_name=${2}
Mixing spaces + tabs

2023-02-16 14:07 UTC, jack-w-shaw commented on tests/suites/deploy_aks/task.sh
> +	juju destroy-controller aks --destroy-all-models --destroy-storage -y
The `includes` helper `destroy_controller` should probably be used here

2023-02-16 14:07 UTC, jack-w-shaw commented on tests/suites/deploy_aks/deploy_aks.sh
> +	juju destroy-model "test-deploy-aks" -y
The `includes` helper `destroy_model` should probably be used here

2023-02-16 14:09 UTC, jack-w-shaw commented
Also QA steps need to be fixed

2023-02-16 14:16 UTC, jack-w-shaw requested changes
Have just realised deploy_aks needs to be added to main.sh

2023-02-16 14:24 UTC, jack-w-shaw commented on tests/suites/deploy_aks/task.sh
> +test_deploy_caas() {
This should be test_deploy_aks

2023-02-16 14:24 UTC, jack-w-shaw commented on tests/suites/deploy_aks/deploy_aks.sh
> +test_deploy_aks() {
This is being executted when you run `./main.sh deploy_aks` without running anything in `task.sh`, so a result the bootstrap is skipped. This should be `run_*` or smth

2023-02-21 11:37 UTC, jack-w-shaw approved these changes

2023-02-21 12:48 UTC, anvial commented
/merge

2023-02-21 13:23 UTC, merged