[JUJU-3349] Resolve resources for DeployFromAPI
juju/juju pull request #15425
Opened 2023-04-05 01:08 UTC by cderici

This is a part of the DeployFromRepository work, continuation of #15315.

Mainly, this change adds the resolveResources to validate resources and pick correct revision when necessary. In addition to 
 #15315, this also handles the case where a `--resource` flag is not used on the cli and juju needs to pick a correct revision for the resource by talking to the CharmHub.

This also refactors some of the code from the resources facade, and tidy up the `addPendingResources` from #15315, by consolidating all the resource resolution logic (i.e. creation of the main resource slice --`[]resource.Resource`--) for all (three) sorts of resources into the `resolveResources` function.

## QA steps

```sh
$ JUJU_DEV_FEATURE_FLAGS=server-side-charm-deploy juju bootstrap localhost test-resources --build-agent --controller-charm-channel 3.2/stable
$ juju add-model test

$ JUJU_DEV_FEATURE_FLAGS=server-side-charm-deploy juju deploy juju-qa-test one --resource foo-file=./tests/suites/resources/foo-file.txt

# check the resources, it should look like the following
$ juju resources one
Resource  Supplied by  Revision
foo-file  admin        2023-04-05T00:12

$ JUJU_DEV_FEATURE_FLAGS=server-side-charm-deploy juju deploy juju-qa-test two

$ juju resources two
Resource  Supplied by  Revision
foo-file  store        2

$ JUJU_DEV_FEATURE_FLAGS=server-side-charm-deploy juju deploy juju-qa-test three --resource foo-file=4

$ juju resources three
Resource  Supplied by  Revision
foo-file  store        4
```

## Notes & Discussion

The main functionality described in the QA above should work, however, there's still a little todo for testing before landing this:
- [ ] facade unit tests will fail, need to fix
- [ ] add some tests for the added functions

I also suspect that this will have some merge conflicts with #15415 when that lands. Looks like it still couldn't get merged because of jenkins issues.

2023-04-06 18:56 UTC, hmlanigan requested changes
Based our conversation, I have a pr up to move apiserver resource repository for ResolveResources into the charmhub core/charm/repository. This will facilitate the changes to be made.

2023-04-12 16:49 UTC, hmlanigan requested changes
A bit more refinement is needed. QA looks good.

2023-04-17 19:24 UTC, hmlanigan reviewed
A few comments while I qa

2023-04-17 19:24 UTC, hmlanigan commented on apiserver/facades/client/application/deployrepository.go
> +			logger.Warningf("Unable to add pending resource %v for application %v", r.Name, appName)
Should be a deployRepoLogger.Errorf and add the error message too to answer why.

2023-04-17 19:24 UTC, hmlanigan commented on apiserver/facades/client/application/deployrepository.go
> +func (v *deployFromRepositoryValidator) resolveResources(
Where is the unit test for this method?

2023-04-17 19:57 UTC, hmlanigan approved these changes
Please make the small changes, then it's good. QA went well.

2023-04-17 23:04 UTC, cderici commented
/merge

2023-04-17 23:38 UTC, merged

2023-05-11 11:19 UTC, manadart commented on apiserver/facades/client/application/deployrepository.go
> +// PendingResourceUpload is only returned for local resources
Comment is wrong.