[JUJU-3447] Enable ModelFirewaller for OpenStack
juju/juju pull request #15525
Opened 2023-04-21 18:21 UTC by jack-w-shaw

This work has already been done for aws. Add OpenStack to the list of
providers which support this

This was mostly trivial, and involved removing a lot of responsibilities
from the OpenStack provider

This has involved updating the go-goose dependency

Also as a flyby fix an bug in config. ssh-allow was defaulting to the
wrong value if the entry was absent. Write a test for this case as well

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing
- [x] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

TBD

2023-04-24 13:44 UTC, hmlanigan reviewed
Why are there no changes to machine security group rules when an application is exposed?

Will continue when the QA steps are updated.

2023-04-24 13:44 UTC, hmlanigan commented on provider/openstack/firewaller.go
> +	if isModelGroup {
```
if !isModelGroup {
    return group, nil
}
```
Reduces indentation and helps with readability.

2023-04-24 16:59 UTC, jack-w-shaw commented on provider/openstack/firewaller.go
> +	rules := []neutron.RuleInfoV2{
The ones that were dropped were the rules opening ports 22 and the apiPort to the world. Now that ModelFirewaller is implemented, these are no longer the responsibility of the provider and will be handled by the firewaller worker

2023-04-25 13:26 UTC, jack-w-shaw commented
> Why are there no changes to machine security group rules when an application is exposed?

I have just tested this. It still works on my machine. I have added this as a QA step

This is ready for another review now, however to get QA working the version in version/version.go will need to be bumped. Either wait for me to merge https://github.com/juju/juju/pull/15533 and rebase, or bump the version yoruself

2023-04-26 17:40 UTC, hmlanigan requested changes
QA: By default, new models do not get port 22 opened, once you set or reset the ssh-allow model config the security group value is set. This log message was found:
```controller-0: 14:34:03 WARNING juju.worker.firewaller Model firewall not found so cannot re-write firewall rule ["22/tcp from 0.0.0.0/0,::/0"]. Ignoring```

Code looks good, just the 1 bug in qa to fix.

2023-05-10 14:17 UTC, closed without merging