[JUJU-3489] Support requires-prompts mode model-config
juju/juju pull request #15559
Opened 2023-05-05 08:51 UTC by jack-w-shaw

This will enable forwards compatibility with future controllers, particularly useful for model migrations

This will require versions 3.2 to bump their minimum migration source versions to 2.9.43

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [ ] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

```sh
$ juju-2.9 bootstrap lxd lxd-2.9
$ juju-2.9 add-model m
$ juju-2.9 deploy ubuntu -n2
$ juju-3.2 bootstrap lxd lxd-3.2
$ juju-2.9 switch lxd-2.9
$ juju-2.9 migrate m lxd-3.2
$ juju-3.2 switch lxd-3.2:admin/m
$ juju-3.2 add-unit ubuntu
```
(verify the extra unit is added successfully)

## Bug reference

https://bugs.launchpad.net/juju/+bug/2015398

2023-05-05 09:31 UTC, tlm requested changes

2023-05-05 09:31 UTC, tlm commented on environs/config/config.go
> +		case "requires-prompts":
Can we have a test for this please ?

2023-05-09 11:14 UTC, jack-w-shaw commented on environs/config/config.go
> +		case "requires-prompts":
Yes of course

2023-05-10 16:17 UTC, anvial approved these changes
QA passed, 

LG2T, but I think we should update the comment (about the number of "modes").

2023-05-10 16:17 UTC, anvial commented on environs/config/config.go
> +// Only two modes are supported at the moment (strict or ""). Empty string
So, means "only three modes ..."

2023-05-11 09:25 UTC, jack-w-shaw commented on environs/config/config.go
> +// Only two modes are supported at the moment (strict or ""). Empty string
Good spot

2023-05-11 09:51 UTC, tlm approved these changes
lgtm

2023-05-11 10:04 UTC, jack-w-shaw commented
/merge

2023-05-11 10:41 UTC, merged