[JUJU-3749] Add SupportedBases to ResolveCharms output
juju/juju pull request #15688
Opened 2023-06-01 15:48 UTC by jack-w-shaw

This is a step towards replacing series with bases in Juju

One of the returns of ResolveCharms was a slice of supported series. Add to this Supported bases and make use of this in the client.

As a flyby rev juju/charm to v11 and juju/collections to v1.0.3. For this reason, you may wish to review the PR one commit at a time. Also replace our usage of go-spew with pretty.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

### Verify you can deploy a charm and refresh it

```
juju deploy postgresql --revision 287 --channel stable
juju refresh postgresql --revision 288
```

Repeat this with:
- build from branch client, build from branch controller
- build from branch client, 3.3 branch controller
- 3.3 branch client, build from branch controller

### Verify kubeflow can be deployed

```
juju deploy kubeflow --trust
```
Repeat this with clients both using charms facade version 6 and 7

2023-06-06 20:25 UTC, hmlanigan requested changes
The charms facade should have a new revision for an old and new version of ResolveCharms with different results. It'll be easier to keep client compatibility and remove the old version in juju 4.x

The commit message of 35fdd05, is missing note of the addition of `--force-base` flag to refresh. That could be a separate commit. The QA steps are missing a test for this change.

2023-06-06 20:28 UTC, hmlanigan commented
@jack-w-shaw JUJU-3479 is an o'Reilly training Jira ticket, which Jira ticket is this change for? I wanted to add some review time.

2023-06-07 09:36 UTC, jack-w-shaw commented
> @jack-w-shaw JUJU-3479 is an o'Reilly training Jira ticket, which Jira ticket is this change for? I wanted to add some review time.

Oops, it's JUJU-3749

2023-06-07 09:49 UTC, jack-w-shaw commented on cmd/juju/application/refresh.go
> +		ForceBase:       c.ForceBase && c.ForceSeries,
Good spot!

2023-06-09 21:07 UTC, hmlanigan reviewed
This is what I have so far, still reviewing. It's a large PR. :-)
QA:

`$ juju deploy ubuntu --base ubuntu@14.04
ERROR ubuntu is not available on the following series: trusty not supported
`

The above output comes from composeSuggestions() in core/charm/repository as part of ResolveCharms

2023-06-13 13:09 UTC, jack-w-shaw commented on api/client/charms/client_test.go
> +	curl2 := charm.MustParseURL("ch:jammy/dummy-1")
Addressed, but have left unresolved so you remember to check since I'm not entirely confident with my solution

2023-06-13 20:58 UTC, hmlanigan reviewed
Current pieces look good. Lots of changes for the better.

Still the one QA fail needs fixing before approval.

2023-06-14 10:06 UTC, jack-w-shaw commented on go.mod
> +	github.com/davecgh/go-spew v1.1.1
Funny this appeared, spew was already a dependency, which was used in one place in one test. I have replaced that with pretty, which moved go-spew back to an indirect

2023-06-14 11:41 UTC, jack-w-shaw commented
> QA:
> 
> `$ juju deploy ubuntu --base ubuntu@14.04 ERROR ubuntu is not available on the following series: trusty not supported `
> 
> The above output comes from composeSuggestions() in core/charm/repository as part of ResolveCharms

@hmlanigan  I'm not convinced this is within the scope of this PR.

This error actually comes from a SeriesSelector in `compatibiltiyPrepareAndDeploy`, not anything to do with ResolveCharm. This should be changed to a base selector, but that's the job for another PR imo

2023-06-14 14:52 UTC, hmlanigan commented
@jack-w-shaw I got the wrong error. I'm thinking of the code in composeSuggestions() in the core charm repository code. As agreed, there is a new Jira ticket to cover that change https://warthogs.atlassian.net/browse/JUJU-4005

2023-06-14 14:52 UTC, hmlanigan approved these changes
lgtm

2023-06-14 14:54 UTC, jack-w-shaw commented
/merge

2023-06-14 15:29 UTC, merged