[JUJU-4328] Inject controllerConfigGetter in agent/meterstatus facade
juju/juju pull request #16124
Opened 2023-08-18 10:57 UTC by anvial

This PR injects controllerConfigService in agent/meterstatus facade. Also, it refactors agent/uniter facade to mock controllerConfigGetter function in unit-tests.

## Checklist

*If an item is not applicable, use `~strikethrough~`.*

- [ ] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [ ] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

```sh
go test github.com/juju/juju/apiserver/facades/agent/meterstatus/... -gocheck.v
go test github.com/juju/juju/apiserver/facades/agent/uniter/... -gocheck.v

juju bootstrap lxd lxd
```

2023-08-21 11:28 UTC, SimonRichardson requested changes
Nearly there. Just a few issues with testing setup.

2023-08-21 11:28 UTC, SimonRichardson commented on apiserver/facades/agent/meterstatus/package_test.go
> +
:+1: Thanks for doing this.

2023-08-21 11:28 UTC, SimonRichardson commented on apiserver/facades/agent/provisioner/provisioner.go
> +	controllerConfigGetter := ctx.ServiceFactory().ControllerConfig()
We probably want to pull this out at the `register.go` file and just pass the service directly.

2023-08-21 11:28 UTC, SimonRichardson commented on apiserver/facades/agent/upgrader/upgrader_test.go
> +	s.controllerConfigGetter = mocks.NewMockControllerConfigGetter(ctrl)
We can't officially do this here as the `gc.C` isn't the same one we pass into the test. This causes much-maligned pain, but the fact is that the error from the test will be incorrect. The gomock controller will be finished at the end of the setup test, not at the end of the test. We need to move this down per test case.

2023-08-21 11:28 UTC, SimonRichardson commented on apiserver/facades/client/machinemanager/instance_information_test.go
> +	s.controllerConfigGetter = mocks.NewMockControllerConfigGetter(ctrl)
Same here, we have to do it, per test. See `setup` in this suite.

2023-08-21 14:01 UTC, anvial commented
/build

2023-08-23 11:03 UTC, SimonRichardson commented on apiserver/facades/agent/meterstatus/meterstatus_test.go
> +
We can't do this. You have to put these in a `setupMocks` and call it for every method.

I'm starting to think the test suite isn't working for us when we're using mocks.

2023-08-23 11:08 UTC, SimonRichardson reviewed
It looks ok, so something doesn't like being torn down.

2023-08-23 11:08 UTC, SimonRichardson commented on apiserver/facades/agent/provisioner/provisioner.go
> +}
I'm thinking these interfaces should be `ControllerConfigService`. So let's try and and standardise on this.

2023-08-23 11:08 UTC, SimonRichardson commented on apiserver/facades/agent/provisioner/register.go
> +	controllerConfigGetter := ctx.ServiceFactory().ControllerConfig()
Move this down with the other service factory call.

2023-08-23 11:08 UTC, SimonRichardson commented on apiserver/facades/schema.json
> +            "model-user"
Ah, we're clearly changed some order here. There isn't much we can do about this. There is a proposal to fix this that people are happy with, but I don't have the time to do it.

2023-08-25 19:28 UTC, anvial commented
Closed in favor https://github.com/juju/juju/pull/16157

2023-08-25 19:29 UTC, anvial commented
Closed in favor https://github.com/juju/juju/pull/16157

2023-08-25 19:29 UTC, closed without merging