[JUJU-4615] Ask user to create local share after installing snap
juju/juju pull request #16266
Opened 2023-09-15 10:46 UTC by anvial

This PR adds a warning that asks to create the .local/share directory manually. This warning should appear every time Juju fails directory existence checks (including installation). This would enhance usability during working with juju strictly confined snap.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

```sh
go test github.com/juju/juju/cmd/juju/commands/... -gocheck.v

snapcraft --use-lxd
sudo snap install <juju_snap_filename>.snap
juju clouds
```

## Links

**Launchpad bug:** https://bugs.launchpad.net/juju/+bug/2031483

**Jira card:** JUJU-4615

2023-09-15 14:07 UTC, SimonRichardson reviewed
I think we should actually move away from the home interface and to [personal-files-interface](https://snapcraft.io/docs/personal-files-interface) . You'll need to ask snap team for approval, but will solve this in a much better way.

2023-09-19 12:34 UTC, SimonRichardson requested changes
We'll be warning about false positives here, instead, we should return typed errors and only show the warning on the home dir issue.

--- 

Alternatively, we could split the home dir and ssh calls into two...

2023-09-20 10:01 UTC, SimonRichardson reviewed
This isn't correct either, as if you're running out side of a snap you'll get this warning.

2023-09-20 10:48 UTC, SimonRichardson approved these changes

2023-09-21 06:55 UTC, anvial commented
/merge

2023-09-21 06:55 UTC, merged

2023-09-27 10:17 UTC, manadart commented on cmd/juju/commands/main.go
> +			ctx.Warningf("Installing juju from a snap, the .local/share directory should be manually created as it is strictly confined.")
A sentence like this, where you state 2 things at the front of the sentence, and then refer to "it" at the back, makes it ambiguous.

It should be something like:
"Installing Juju in a strictly confined Snap. To ensure correct operation, create the .local/share directory manually."