Fix bug where "use --force" prompt is not displayed when deploying
juju/juju pull request #16385
Opened 2023-10-05 12:16 UTC by jack-w-shaw

For some reason our series selector was not returning an UnsupportedSeries error when it should have been, instead duplicating the text of the error and returning a generic error

This means downstream error type checks were failing

Also remove some duplicated code/unnecessary code. It turns out that our resolver emthods do not return return UnsupportedSeries errors

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

Run the `deploy` integration tests

Unit tests pass

```
$ juju deploy kafka --base ubuntu@20.04 --revision 123 --channel stable
ERROR series "focal" not supported by charm, the charm supported series are: jammy. Use --force to deploy the charm anyway.
```

2023-10-05 13:06 UTC, hmlanigan commented
@jack-w-shaw We should understand why the errors changed and we're not using the UnsupportedBaseError any longer, rather than just removing the checks. Have root cause of the failure.

2023-10-05 13:29 UTC, jack-w-shaw commented
@hmlanigan turns out figuring out exactly what happened there is more tricky than I expected, so I have removed those changes from this PR. They were a bit of a flyby anyway

2023-10-12 20:28 UTC, hmlanigan requested changes
This PR is missing the updates for local charms.

I added a manifest.yaml to  ./testcharms/charms/lxd-profile:
```
bases:
- architectures:
  - amd64
  channel: '20.04'
  name: ubuntu
- architectures:
  - amd64
  channel: '18.04'
  name: ubuntu
- architectures:
  - amd64
  channel: '16.04'
  name: ubuntu
```
```
$ juju deploy ./testcharms/charms/lxd-profile --base ubuntu@22.04
ERROR series "jammy" not supported by charm, the charm supported series are: focal
```

2023-12-11 10:53 UTC, SimonRichardson commented
@jack-w-shaw is this required to still be open, otherwise, we should close it.

2024-02-07 15:38 UTC, closed without merging