Add known hosts to manual provisioner
juju/juju pull request #16662
Opened 2023-12-02 00:57 UTC by DanielKenichi

Automatically provisioning machines via SSH is interesting for the implementation of models. Juju and can accept manual provisioning on its machines. However, manual provisioning of a new machine asks for host confirmation by the user interactively. To make the task of automation easier, it is interesting to provide an option of defining the set of hosts in a specified file.

To quickly verify this new option, first build the project with the applied changes. Then, bootstrap a localhost cloud with ` juju bootstrap localhost test-controller` and launch a linux container with ` lxc launch ubuntu:22.04` . Add a test model with `juju add-model foo`  and try `juju  add-machine --known-hosts <path-to-known-hosts-file> ssh:ubuntu@<lxd instance ip>`.  

Verify that the known_hosts file used is not the default located on ~/.ssh, and that the specified file is used instead.

2023-12-13 06:49 UTC, tlm commented
Thanks @DanielKenichi for your contribution. Much appreciated and definitely looks like a good addition to Juju.

May I ask if there is a specific version of Juju you would like to see this available in? At the moment this PR is currently targeting our master branch which will end up in Juju 4.0 release that won't happen for a little while yet.

In the meantime I will start having a look at this PR and get you some feedback. Would you also be able to let us know how much more you would be willing to work on this PR if it needs a little bit of extra work to get it across the line?

Cheers

2023-12-16 14:14 UTC, DanielKenichi commented
Heyo @tlm!

Thanks for the feedback! We really appreciate it!

There isn't a specific version of juju we would like to see it in, so I think there is no problem if it ends up on Juju 4.0.

About working more on it, as long as there is no problem with me being more active on my freetime on weekends, I am willing to work as much as it needs since I think it is a good and fun experience to work with the codebase. 

My friends @migeyel @SaraO3O and @SnakeZ0 also had a part on this so I will be keeping them in touch with the feedbacks as well ok?

2024-01-15 04:06 UTC, tlm reviewed
Thanks for the work thus far. I have left some comments for your considerations.

I am also thinking some of these ssh functions are becoming long in the tooth for ssh options getting passed to them and wondering if we should introduce an options ssh structure into the mix.

If this is something you don't feel comfortable with designing I am happy to put a commit on this PR with a design.

Cheers
tlm

2024-02-07 15:22 UTC, DanielKenichi commented on cmd/juju/machine/add.go
> +		KnownHosts:     c.KnownHosts,
Can it be something simple like that on the [Adds sanity check for KnownHostsFile](https://github.com/juju/juju/pull/16662/commits/ea23671f3c3e264a7435a7f6cc79abffe7f63f8f) commit?

2024-02-07 15:40 UTC, SimonRichardson commented
/build

2024-02-07 16:34 UTC, DanielKenichi commented on cmd/juju/machine/add.go
> +		KnownHosts:     c.KnownHosts,
Hmmm actually I think that I forgot to check if KnownHostsFile is not a zero value string in this case. ReadFile will probably drop an error if it receives a "" as parameter.

Is it okay to ammend the last commit with this check? Or should I make another commit for it?

2024-03-05 01:12 UTC, DanielKenichi commented
/build

2024-03-05 17:34 UTC, DanielKenichi commented
Hi @tlm!

would you mind having a look at the changes done after your last review?

2024-03-25 13:22 UTC, SimonRichardson commented
/build

2024-05-07 21:54 UTC, DanielKenichi commented
@hpidcock sorry for taking some time here, but finally fixed the merge conflicts

2024-07-05 09:22 UTC, hpidcock requested changes

2024-07-05 09:22 UTC, hpidcock commented on cmd/juju/machine/add.go
> +		err := os.WriteFile(c.KnownHostsFile, []byte(""), 0644)
Why do we nuke the known_hosts file here?

2024-07-05 09:22 UTC, hpidcock commented on environs/manual/sshprovisioner/sshprovisioner.go
> +	options.SetKnownHostsFile(knownHostsFile)
We should only call this if we actually have something to set. It is important to keep intent here, even if it doesn't do anything with an empty string.

2024-07-05 09:22 UTC, hpidcock commented on environs/manual/sshprovisioner/sshprovisioner.go
> +	options.SetKnownHostsFile(knownHostsFile)
Same with here.

2024-07-05 09:22 UTC, hpidcock commented on environs/manual/sshprovisioner/sshprovisioner.go
> +	options.SetKnownHostsFile(knownHostsFile)
Same here too.

2024-07-05 09:22 UTC, hpidcock commented on environs/manual/sshprovisioner/sshprovisioner.go
> +	options.SetKnownHostsFile(knownHostsFile)
Here too.

2024-07-24 14:59 UTC, SimonRichardson commented
Closing for now, as there is no movement. More than welcome to reopen if you still want to work on it.

2024-07-24 14:59 UTC, closed without merging