Always verify result exists when looking for map entries.
juju/juju pull request #16822
Opened 2024-01-23 20:11 UTC by hmlanigan

Getting a value from a map and converting it to a string without verifying the value exists first can cause failures:
 "interface conversion: interface {} is nil, not string"

There was a juju bug seen in the terraform provider for juju where add model for 3.3.x and 3.4 controllers failed with the string above. Looking at tracing in the controller led to the issue:

```
2024-01-23 19:42:17 CRITICAL juju.rpc server.go:557 panic running request {MethodCaller:0xc000960150 transformErrors:0x3a773a0 hdr:{RequestId:2 Request:{Type:ModelManager Version:9 Id: Action:CreateModel} Error: ErrorCode: ErrorInfo:map[] Version:1}} with arg {Name:east-two OwnerTag:user-admin Config:map[] CloudTag: CloudRegion: CloudCredentialTag:}: interface conversion: interface {} is nil, not string
goroutine 6178 [running]:
runtime/debug.Stack()
        /snap/go/10489/src/runtime/debug/stack.go:24 +0x5e
github.com/juju/juju/rpc.(*Conn).runRequest.func1()
        /home/heather/work/src/github.com/juju/juju/rpc/server.go:558 +0x6e
panic({0x6862080?, 0xc000961d70?})
        /snap/go/10489/src/runtime/panic.go:914 +0x21f
github.com/juju/juju/controller/modelmanager.ModelConfigCreator.NewModelConfig({0x7889d60, 0xc001040268}, {{0xc002a81171, 0x3}, {0xc002a81161, 0x9}, {0xc0029ede20, 0x9}, {0xc00141eb58, 0x18}, ...}, ...)
        /home/heather/work/src/github.com/juju/juju/controller/modelmanager/createmodel.go:88 +0x552
github.com/juju/juju/apiserver/facades/client/modelmanager.(*ModelManagerAPI).newModelConfig(0xc000f042c0, {{0xc002a81171, 0x3}, {0xc002a81161, 0x9}, {0xc0029ede20, 0x9}, {0xc00141eb58, 0x18}, {0x0, ...}, ...}, ...)
        /home/heather/work/src/github.com/juju/juju/apiserver/facades/client/modelmanager/modelmanager.go:184 +0x359
github.com/juju/juju/apiserver/facades/client/modelmanager.(*ModelManagerAPI).newModel(_, {{0xc002a81171, 0x3}, {0xc002a81161, 0x9}, {0xc0029ede20, 0x9}, {0xc00141eb58, 0x18}, {0x0, ...}, ...}, ...)
....
```

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- ~[ ] Go unit tests, with comments saying what you're testing~
- [x] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Fixes errors in https://github.com/juju/juju/actions/workflows/terraform-smoke.yml for 3.3 and 3.4 branches. Can also be seen as resolved with reproduction steps in [bug 384](https://github.com/juju/terraform-provider-juju/issues/385)

## Links
JUJU-5330
https://github.com/juju/terraform-provider-juju/issues/385

2024-01-23 20:31 UTC, hmlanigan commented
@nvinuesa I'm wondering if this means your fix from #16394 will no work with OCI/Vsphere models created via Terraform?

2024-01-23 22:55 UTC, nvinuesa reviewed
I think we can also find a unit test to validate this error, but I couldn't come up with one yet

2024-01-24 08:34 UTC, nvinuesa requested changes
We should add this test that reproduces the bug seen in terraform (authorized keys present in the controller config and not provided to NewModel):
```
func (s *ModelConfigCreatorSuite) TestCreateModelMissingAuthorizedKeys(c *gc.C) {
	modelTag := names.NewModelTag("deadbeef-0bad-400d-8000-4b1d0d06f00d")
	modelConfig, err := config.New(
		config.UseDefaults,
		coretesting.Attrs{
			"uuid":                      modelTag.Id(),
			"type":                      "someprovider",
			"name":                      "testmodel",
			"firewall-mode":             config.FwInstance,
			"ssl-hostname-verification": true,
			"secret-backend":            "auto",
			"development":               false,
		},
	)
	c.Check(err, jc.ErrorIsNil)

	authorizedKeys := `
			ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLNN6YxkRJ8liYGh9qymZi23lDRlFrD3ujGfcgkjqa7vOqBHJaWklaIW4vFX0XkYuhgnDlXREi7RRK+4I0XBD051LxADobguLXyeGoOhSRlLLThYMF7Ui8nNylLxY0MYpKUIE6ejve2DHtrwGXBJBUXGJr8z5gKuIZD9J39B3ld1e7v2fpK3SqQ84H8mSZxPBbZqA0NIoq9wl+ke780fYsDxBpsAJhaZW2SjCqcrmNc3m9HgYwzeHhsXDZN2xonoyK2UVMGCsqR0vTHZNpnhME4FdGsmK6WIRMq+z5Mxrw3rSYIgbWi1uACfSsPeBMXmkWORujZrf1w1OKoy1dKeWp juju-client-key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwvae4M/oc+p5d3vj5TBS/4Mx+us5nVuMBgpYCQYq1Bk+QyfyefVfhQwuILAhmzehKnxUse1kGERQ0wNCtn7wU/HhvAuzQBWkxMvShyO9x7GS+4cDEGhkhMGGCu5NvBBCvp24+WdNeqsvoMDRHtBO1kFVc3FQZ01IjR+FTAICW5hE8e7ssCFK+pIDa8TI44rz41grytVJ1iACvaXc7nTyFZg95EXxSurPv0EnO82Gxfdt4bkiSXPXQqNcTLNiJ2oKRyDVYAjZNIr2Yf+UGCK9fy0VAdM7dwVZ9FOQX430blrDpDNo096+FXs2MoRB5SLzueZo2Eurya5OxcYpfIkdrzNpgAUgiL7cVURCh0+xJrIX/Ow9Axle+GvDcWAS9aZsRO+nsJ9Mry0zGWN/2IAEEZY9KVr7YO8xcCJ/yZ2gFXhyRAjD2oNBBrIfwpFNHZ35TbT5znmTX1wrJapLPyXqosGHZed8FkTDIyocCZzDlB0PpuBzUtjWp8gKwrPNsBGzTMvso3Qah3xOiznc7DTBCeSf2mqsX+6iY6p2k4YmF9LST+hepbgF4WW8Y3xgSuJ510TE3wtf/QZXDjQY+r7+yLraHSlE6CzQvL07snDyn4NHqfGw3GMAT71dpoa7WVGWW4HdcpCa8ALCtOx1GpyaydFANwNuwr1wOMQuY/9R5dw== juju-system-key
`
	customBaseConfig, err := config.New(
		config.UseDefaults,
		coretesting.FakeConfig().Merge(coretesting.Attrs{
			"type":            "fake",
			"restricted":      "area51",
			"agent-version":   "2.0.0",
			"authorized-keys": authorizedKeys,
		}),
	)

	cloudSpec := environscloudspec.CloudSpec{Type: "fake"}
	_, err = s.creator.NewModelConfig(cloudSpec, customBaseConfig, coretesting.Attrs(modelConfig.AllAttrs()))
	c.Check(err, jc.ErrorIsNil)
}
```

2024-01-25 18:59 UTC, hmlanigan commented on controller/modelmanager/createmodel.go
> +			}
I went in a different direction after discovering my fix created a regression.

2024-01-26 08:57 UTC, nvinuesa approved these changes
Code looks good. While QAing I cannot ssh into the machines though. This is probably an issue with the terraform provider? Because when I create a model and deploy manually using the juju-cli it works so no regression.

2024-01-26 09:37 UTC, jack-w-shaw commented
Merging in myself, because we want to do a release today and I assume @hmlanigan will want this in

2024-01-26 09:38 UTC, jack-w-shaw commented
/merge

2024-01-26 09:38 UTC, merged

2024-01-26 13:34 UTC, hmlanigan commented
@nvinuesa The QA steps used `lxc exec` instead of `ssh` because `ssh` won't work without using a `juju_ssh_key` resource in terraform. I wanted to keep the steps simpler.