Change proxyupdater to use model config service
juju/juju pull request #17421
Opened 2024-05-24 12:57 UTC by barrettj12

Modify the proxyupdater agent facade to use a model config service instead of getting model config from state.

Includes corresponding test changes. I've modified the tests to use gomock-generated mocks for both `ControllerConfigService` and `ModelConfigService`, as per agreed convention.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- ~[ ] Comments saying why design decisions were made~
- [x] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Run unit tests.

Manual QA steps:

```console
$ juju bootstrap lxd c
$ juju switch controller

# Check existing proxy settings on disk
$ juju exec --machine 0 -- cat /etc/juju-proxy.conf

# Change proxy settings in model config
$ juju model-config http-proxy='foo'

# Check proxy settings have been updated
$ juju exec --machine 0 -- cat /etc/juju-proxy.conf
export http_proxy=foo
export HTTP_PROXY=foo
export no_proxy=...
export NO_PROXY=...
```

## Links

**Jira card:** JUJU-6057

2024-05-24 14:31 UTC, barrettj12 commented
/build

2024-05-26 21:21 UTC, hpidcock requested changes

2024-05-26 21:21 UTC, hpidcock commented on apiserver/facades/agent/proxyupdater/proxyupdater_test.go
> +	s.modelConfigService = &stubModelConfigService{}
Looking at the facade code, I think moving to mocks would be trivial. Can we please change to that?

2024-05-26 21:22 UTC, hpidcock commented
Please add QA steps that test changing proxy settings and seeing them change on an agent.

2024-05-28 01:22 UTC, tlm reviewed
Thank you for the work. When you are ready please updating testing steps and drag this PR out of draft. Also Jira card into current sprint.

2024-05-28 01:22 UTC, tlm commented on apiserver/facades/agent/proxyupdater/proxyupdater.go
> +type ModelConfigService interface {
Can we please move this into a `services.go` file and also add comments for the functions. Comments can be copied from the service.

2024-06-03 04:57 UTC, hpidcock approved these changes
Thanks for the QA steps. Manually testing passed.

2024-06-03 05:48 UTC, tlm approved these changes
lgtm

2024-06-03 22:12 UTC, barrettj12 commented
/merge

2024-06-03 22:13 UTC, merged