[WIP] feat(dqlite): WatchModelMachines on machine WatchableService
juju/juju pull request #17489
Opened 2024-06-10 01:25 UTC by cderici

This adds the following:

- Passes the servicefactorygetter to the provisioner worker through the model manifold (into provisioner manifold), which is how the provisioner gets a hold of the machine domain service to call on the watchable services on the machine domain (e.g. WatchModelMachines).
- Adds a `WatchableService` on top of the machine service, and implements the `WatchModelMachines` (old one is at `state/watcher.go`) on top of that `WatchableService`.
- Ties these two together by having the provisioner call the new `WatchModelMachines` on dqlite directly through the servicefactory.

Right now it's having some build issues, and it needs a cleanup.

```
 $ make build
Generating facade schema...
Building github.com/juju/juju/cmd/jujuc for linux/amd64
Building github.com/juju/juju/cmd/jujud for linux/amd64
github.com/canonical/go-dqlite/internal/bindings
github.com/canonical/go-dqlite/internal/bindings: build constraints exclude all Go files in /home/caner/go/pkg/mod/github.com/canonical/go-dqlite@v1.21.0/internal/bindings
github.com/juju/juju/internal/database/txn
# github.com/juju/juju/internal/database/txn
internal/database/txn/errors.go:24:28: undefined: sqlite3.ErrLocked
internal/database/txn/errors.go:24:65: undefined: sqlite3.ErrBusy
make: *** [Makefile:377: /home/caner/work/juju/_build/linux_amd64/bin/jujud] Error 1
```

## Checklist

- [ ] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [ ] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

## Documentation changes

## Links

**Launchpad bug:** https://bugs.launchpad.net/juju/+bug/

**Jira card:** JUJU-

2024-06-10 06:08 UTC, hpidcock commented
The provisioner worker is run on machines, they cannot access the service factory. We need to continue to use the facade calls here.

2024-06-10 06:40 UTC, SimonRichardson requested changes
@hpidcock is indeed correct here. You can't use the services directly in the provisioner. The error you got is on purpose. Essentially, you're trying to import the database into `jujud`, which has no concept of a database and can only communicate to the database via the API server, which lives in `jujud-controller`.

There are two solutions:

 1. Go via the API server (facades) for all calls.
 2. For jujud-controller provisioner, use the service factory directly and for jujud go via the API server.

2024-06-11 20:15 UTC, cderici commented
/build

2024-06-12 22:35 UTC, cderici commented
/build

2024-06-13 01:53 UTC, cderici commented
/build

2024-06-14 09:04 UTC, SimonRichardson commented on domain/machine/watcher_test.go
> +	watcherC.AssertChange(uuid)
This isn't quite correct, instead I'd expect one change when we create machine, then one for when we delete the machine.

```suggestion
	// Create a machine
	uuid, err := machineService.CreateMachine(context.Background(), "machine-1")
	c.Assert(err, gc.IsNil)
	
	// Ensure that the changestream is idle.
	s.ModelSuite.AssertChangeStreamIdle(c)
	
	// Assert the first change
	watcherC.AssertChange(uuid)
	
	// Delete the machine
	err = machineService.DeleteMachine(context.Background(), "machine-1")
	c.Assert(err, gc.IsNil)

	// Ensure that the changestream is idle.
	s.ModelSuite.AssertChangeStreamIdle(c)
	
	watcherC.AssertChange(uuid)
```

2024-06-19 10:34 UTC, manadart reviewed
You're trying to do too much at once here.

Land the domain changes first, along with the signature changes that include the UUID.

I'm pretty sure the error is caused by your watcher returning machine UUIDs, where the old one returned _machine_ IDs. When you get the change and try to query them, they are not found.

The firewaller and instance-poller should be accessing the service directly as we discussed before. It's only the on-machine provisioner that needs to use the API.

2024-06-19 10:34 UTC, manadart commented on domain/machine/state/state.go
> +		newUUID = machineUUID.String()
We should be doing this up in the service layer. If retries are invoked, we're generating them over again.

2024-06-26 00:22 UTC, closed without merging

2024-06-26 00:22 UTC, cderici commented
Closing this in favor of a new one. 1) it's redundant to try to figure out the conflicts (things have moved around), 2) firewaller and instancepoller needs to access the services directly so those parts will be newly written anyways.