style(sqlair): use SQLair in the objectstore domain
juju/juju pull request #17536
Opened 2024-06-18 09:57 UTC by Aflynn50

This PR switches to use SQLair in the object store, fixes a small bug, and adds a doc.go

The type objectstore.Metadata was local to the objectstore domain. With
the transition to SQLair I required a very similar type just in the
state with the db tags on it. For this reason I have moved the type to
state, tagged it, and replaced it in the service with the core object
store metadata type.

The UUID generation was done in the service layer but now can be done
simply in the state layer.

A small bug is also fixed where if a second piece of metadata pointing to
an object of the same shape were inserted then the path would not get
put into the path table due to an early return.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [x] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps
```
 TEST_PACKAGES="./domain/objectstore/... -count=1 " TEST_FILTER="Suite" make run-go-tests
```

### Test object store in HA
Start minio as to use as the s3 object store.
```
docker run -p 9000:9000 -p 9001:9001 \
  quay.io/minio/minio server /data --console-address ":9001"
```

Go to http://localhost:9001/access-keys and add an access key, keeping note of the key and secret as env var `S3_KEY` and `S3_SECRET`.
Also make a note of the IP for minio (not the `localhost` one) as `IP_ADDRESS`.

Now bootstrap with the s3 object store specified.
```
$ bootstrap lxd test --build-agent --config="object-store-type=s3" --config="object-store-s3-endpoint=http://${IP_ADDRESS}:9000" --config="object-store-s3-static-key=${S3_KEY}" --config="object-store-s3-static-secret=${S3_SECRET}"
```

Now its deployed try going into HA:
```
$ juju enable-ha
$ juju add-model default
$ juju deploy juju-qa-test --resource foo-file="./tests/suites/resources/foo-file.txt"
$ juju deploy ubuntu -n 3
$ juju destroy-model default
```

## Documentation changes
Added doc.go to the domain

## Links

**Jira card:** [JUJU-5628](https://warthogs.atlassian.net/browse/JUJU-5628)

[JUJU-5628]: https://warthogs.atlassian.net/browse/JUJU-5628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-21 09:09 UTC, SimonRichardson requested changes
You're going to need to do the full setup of QA steps here.

 - Deploy
 - Deploy with resources
 - HA
 - ...

2024-06-24 11:42 UTC, Aflynn50 commented
> You're going to need to do the full setup of QA steps here.
> 
>     * Deploy
> 
>     * Deploy with resources
> 
>     * HA
> 
>     * ...

Done full QA, good call because it did uncover a bug!

2024-06-24 15:14 UTC, SimonRichardson reviewed
Going in the right direction. Few nips and tucks.

2024-06-24 15:14 UTC, SimonRichardson commented on domain/objectstore/state/types.go
> +func (m dbMetadata) ToCoreObjectStoreMetadata() coreobjectstore.Metadata {
Add comment.

2024-06-24 16:12 UTC, SimonRichardson approved these changes

2024-06-25 06:56 UTC, Aflynn50 commented
/merge

2024-06-25 06:57 UTC, merged