chore: merge 3.6
juju/juju pull request #18162
Opened 2024-10-01 08:23 UTC by ycliuhw

Merge branch '3.6' into main:
- https://github.com/juju/juju/pull/17994
- https://github.com/juju/juju/pull/17999
- https://github.com/juju/juju/pull/18009
- https://github.com/juju/juju/pull/17980
- https://github.com/juju/juju/pull/18019
- https://github.com/juju/juju/pull/18057
- https://github.com/juju/juju/pull/17960
- https://github.com/juju/juju/pull/18070
- https://github.com/juju/juju/pull/18081
- https://github.com/juju/juju/pull/18083
- https://github.com/juju/juju/pull/18080
- https://github.com/juju/juju/pull/18085
- https://github.com/juju/juju/pull/18100
- https://github.com/juju/juju/pull/18073
- https://github.com/juju/juju/pull/18123
- https://github.com/juju/juju/pull/18111
- https://github.com/juju/juju/pull/18105
- https://github.com/juju/juju/pull/18124
- https://github.com/juju/juju/pull/18128
- https://github.com/juju/juju/pull/18052
- https://github.com/juju/juju/pull/18095
- https://github.com/juju/juju/pull/18126
- https://github.com/juju/juju/pull/17699
- https://github.com/juju/juju/pull/18022
- https://github.com/juju/juju/pull/18154
- https://github.com/juju/juju/pull/18155

# Conflicts:
#       .github/workflows/static-analysis.yml
#       apiserver/facades/client/application/deploy_test.go
#       apiserver/facades/client/applicationoffers/applicationoffers.go
#       apiserver/facades/client/applicationoffers/applicationoffers_test.go
#       cmd/juju/action/common.go
#       cmd/juju/action/run.go
#       cmd/juju/action/showoperation.go
#       cmd/juju/action/showtask.go
#       cmd/juju/controller/config.go
#       cmd/juju/metricsdebug/collectmetrics.go
#       cmd/jujud/agent/agenttest/agent.go
#       controller/config.go
#       core/cache/controller.go
#       database/txn/transaction.go
#       go.mod
#       go.sum
#       internal/mongo/mongo_test.go
#       internal/mongo/service.go
#       internal/upgrades/upgradevalidation/upgrade.go
#       internal/worker/diskmanager/diskmanager.go
#       internal/worker/uniter/relation/resolver.go
#       internal/worker/uniter/relation/resolver_test.go
#       internal/worker/uniter/runner/context/context_test.go
#       mongo/mongotest/mongoservice_mock.go
#       tests/suites/secrets_iaas/juju.sh
#       tests/suites/secrets_iaas/vault.sh
#       tests/suites/static_analysis/lint_go.sh
#       worker/modelcache/worker_test.go
#       worker/uniter/runner/jujuc/add-metric.go
#       worker/uniter/runner/jujuc/add-metric_test.go
#       worker/uniter/runner/jujuc/k8s-raw-get_test.go
#       worker/uniter/runner/jujuc/k8s-raw-set_test.go
#       worker/uniter/runner/jujuc/k8s-spec-get_test.go
#       worker/uniter/runner/jujuc/k8s-spec-set.go
#       worker/uniter/runner/jujuc/k8s-spec-set_test.go

2024-10-02 07:22 UTC, ycliuhw commented
Hey @SimonRichardson @jack-w-shaw @manadart @Aflynn50 
this forward merge has conflicts that were introduced on your end, so it would be best for you to review it.

2024-10-02 07:30 UTC, SimonRichardson approved these changes
This seems ok.

2024-10-02 10:21 UTC, Aflynn50 approved these changes
The changes from me in this look good

2024-10-02 14:05 UTC, ycliuhw commented
/merge

2024-10-02 14:38 UTC, manadart reviewed
My stuff (relation hook resolver) looks OK.

2024-10-02 14:38 UTC, manadart commented on doc/MongoDB-and-Consistency.md
> +<!-- TODO(gfouillet): do not merge into 4.0, or delete whenever merged (reason: related to mongodb) -->
Address this.

2024-10-02 23:14 UTC, ycliuhw commented on doc/MongoDB-and-Consistency.md
> +<!-- TODO(gfouillet): do not merge into 4.0, or delete whenever merged (reason: related to mongodb) -->
Yep, removed.

2024-10-03 05:29 UTC, ycliuhw commented
/build

2024-10-03 05:57 UTC, hpidcock requested changes
what is with the git history here being re-written?

2024-10-08 00:00 UTC, hpidcock commented
I will force merge this after review, static-analysis job is too pedantic.

2024-10-08 00:02 UTC, hpidcock approved these changes

2024-10-08 00:03 UTC, merged