fix: remove instance data checks on caas provisioning
juju/juju pull request #18305
Opened 2024-10-30 16:14 UTC by nvinuesa

A wrong set of checks was incorrectly added on
https://github.com/juju/juju/pull/18165, which added checks on instance data and therefore machine retrieval for caas apps provisioning. This returns an error when trying to deploy.

## QA steps

Deploying on microk8s should test this codepath:

```sh
$ make microk8s-operator-update
$ juju bootstrap microk8s c
$ juju add-model m
```
Workaround the model config bug:
```sh
$ juju model-config workload-storage="microk8s-hostpath"
```
Then deploy:
```
$ juju deploy postgresql-k8s --trust
```
Application should reach a idle state and no errors observed on debug-log.

## Links

**Jira card:** JUJU-

2024-10-30 16:23 UTC, SimonRichardson requested changes
I know you didn't test this :)

Please can you ensure that all QA steps are correct before we approve.

2024-10-31 09:44 UTC, SimonRichardson approved these changes

2024-10-31 13:13 UTC, manadart approved these changes
Still got the timing window issue preventing k8s deployment _sometimes_, but this fixes the issue I observed.

2024-10-31 13:17 UTC, nvinuesa commented
/merge

2024-10-31 13:17 UTC, merged